# An Introduction to Python

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Values" data-toc-modified-id="Values-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Values</a></span><ul class="toc-item"><li><span><a href="#Integers" data-toc-modified-id="Integers-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Integers</a></span></li><li><span><a href="#Floats" data-toc-modified-id="Floats-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Floats</a></span></li><li><span><a href="#String-values" data-toc-modified-id="String-values-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>String values</a></span></li><li><span><a href="#Boolean-values" data-toc-modified-id="Boolean-values-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Boolean values</a></span></li><li><span><a href="#The-None-value" data-toc-modified-id="The-None-value-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>The None value</a></span></li></ul></li><li><span><a href="#Expressions-and-operators" data-toc-modified-id="Expressions-and-operators-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Expressions and operators</a></span><ul class="toc-item"><li><span><a href="#Order-of-operations" data-toc-modified-id="Order-of-operations-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Order of operations</a></span><ul class="toc-item"><li><span><a href="#(Optional)-Deep-dive-into-Order-of-Operations" data-toc-modified-id="(Optional)-Deep-dive-into-Order-of-Operations-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>(Optional) Deep dive into Order of Operations</a></span></li><li><span><a href="#Exercise-–-where-to-put-the-parenthesis?" data-toc-modified-id="Exercise-–-where-to-put-the-parenthesis?-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>Exercise – where to put the parenthesis?</a></span></li></ul></li><li><span><a href="#Concatination" data-toc-modified-id="Concatination-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Concatination</a></span></li></ul></li><li><span><a href="#Variables-and-statements" data-toc-modified-id="Variables-and-statements-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Variables and statements</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Quick-sidenote-–-the-print()-function" data-toc-modified-id="Quick-sidenote-–-the-print()-function-3.0.1"><span class="toc-item-num">3.0.1&nbsp;&nbsp;</span>Quick sidenote – the <code>print()</code> function</a></span></li></ul></li><li><span><a href="#Assigning-variables" data-toc-modified-id="Assigning-variables-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Assigning variables</a></span></li><li><span><a href="#Variables-and-strings" data-toc-modified-id="Variables-and-strings-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Variables and strings</a></span><ul class="toc-item"><li><span><a href="#String-formatting-–-inserting-variables-into-string-values" data-toc-modified-id="String-formatting-–-inserting-variables-into-string-values-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>String formatting – inserting variables into string values</a></span></li><li><span><a href="#(Deepdive)-–-Long-strings,-string-literals-and-the-escape-character-\" data-toc-modified-id="(Deepdive)-–-Long-strings,-string-literals-and-the-escape-character-\-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>(Deepdive) – Long strings, string literals and the escape character <code>\</code></a></span><ul class="toc-item"><li><span><a href="#More-on-tripple-quote-strings" data-toc-modified-id="More-on-tripple-quote-strings-3.2.2.1"><span class="toc-item-num">3.2.2.1&nbsp;&nbsp;</span>More on tripple quote strings</a></span></li><li><span><a href="#String-literals-and-the-backslash-\" data-toc-modified-id="String-literals-and-the-backslash-\-3.2.2.2"><span class="toc-item-num">3.2.2.2&nbsp;&nbsp;</span>String literals and the backslash <code>\</code></a></span></li><li><span><a href="#Exercise-–-write-a-letter!" data-toc-modified-id="Exercise-–-write-a-letter!-3.2.2.3"><span class="toc-item-num">3.2.2.3&nbsp;&nbsp;</span>Exercise – write a letter!</a></span></li></ul></li></ul></li><li><span><a href="#Changing-variables-–-Operators-and-assignment-statements" data-toc-modified-id="Changing-variables-–-Operators-and-assignment-statements-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Changing variables – Operators and assignment statements</a></span><ul class="toc-item"><li><span><a href="#Augmented-assignment-operators" data-toc-modified-id="Augmented-assignment-operators-3.3.1"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span>Augmented assignment operators</a></span></li></ul></li><li><span><a href="#Multiple-assignment-statements" data-toc-modified-id="Multiple-assignment-statements-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Multiple assignment statements</a></span></li><li><span><a href="#(Optional)-More-about-readability-–-the-zen-of-Python" data-toc-modified-id="(Optional)-More-about-readability-–-the-zen-of-Python-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>(Optional) More about readability – the zen of Python</a></span></li><li><span><a href="#Exercise-–-string-concatination-and-variables" data-toc-modified-id="Exercise-–-string-concatination-and-variables-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Exercise – string concatination and variables</a></span></li></ul></li><li><span><a href="#Comparing-values" data-toc-modified-id="Comparing-values-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Comparing values</a></span><ul class="toc-item"><li><span><a href="#Comparison-operators" data-toc-modified-id="Comparison-operators-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Comparison operators</a></span></li><li><span><a href="#Boolean-operators" data-toc-modified-id="Boolean-operators-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Boolean operators</a></span><ul class="toc-item"><li><span><a href="#The-and-operator" data-toc-modified-id="The-and-operator-4.2.1"><span class="toc-item-num">4.2.1&nbsp;&nbsp;</span>The <code>and</code> operator</a></span></li><li><span><a href="#The-or-operator" data-toc-modified-id="The-or-operator-4.2.2"><span class="toc-item-num">4.2.2&nbsp;&nbsp;</span>The <code>or</code> operator</a></span></li><li><span><a href="#The-not-operator" data-toc-modified-id="The-not-operator-4.2.3"><span class="toc-item-num">4.2.3&nbsp;&nbsp;</span>The <code>not</code> operator</a></span></li><li><span><a href="#Boolean-operators-–-examples" data-toc-modified-id="Boolean-operators-–-examples-4.2.4"><span class="toc-item-num">4.2.4&nbsp;&nbsp;</span>Boolean operators – examples</a></span></li></ul></li><li><span><a href="#Exercise-–-insert-the-correct-operators" data-toc-modified-id="Exercise-–-insert-the-correct-operators-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Exercise – insert the correct operators</a></span></li></ul></li><li><span><a href="#Flow-Control-Statements" data-toc-modified-id="Flow-Control-Statements-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Flow Control Statements</a></span><ul class="toc-item"><li><span><a href="#The-if-statement" data-toc-modified-id="The-if-statement-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>The <code>if</code>-statement</a></span></li><li><span><a href="#The-else-statement" data-toc-modified-id="The-else-statement-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>The <code>else</code>-statement</a></span></li><li><span><a href="#The-elif-statement" data-toc-modified-id="The-elif-statement-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>The <code>elif</code>-statement</a></span></li><li><span><a href="#(Optional)-&quot;Truthy&quot;-and-&quot;Falsy&quot;-values" data-toc-modified-id="(Optional)-&quot;Truthy&quot;-and-&quot;Falsy&quot;-values-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>(Optional) "Truthy" and "Falsy" values</a></span></li><li><span><a href="#Exercise-–-type-the-end-of-the-story!" data-toc-modified-id="Exercise-–-type-the-end-of-the-story!-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>Exercise – type the end of the story!</a></span></li></ul></li><li><span><a href="#Functions" data-toc-modified-id="Functions-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Functions</a></span><ul class="toc-item"><li><span><a href="#Built-in-Functions" data-toc-modified-id="Built-in-Functions-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Built-in Functions</a></span></li><li><span><a href="#The-standard-library-and-modules" data-toc-modified-id="The-standard-library-and-modules-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>The standard library and modules</a></span><ul class="toc-item"><li><span><a href="#Exercise-–-the-coin-toss" data-toc-modified-id="Exercise-–-the-coin-toss-6.2.1"><span class="toc-item-num">6.2.1&nbsp;&nbsp;</span>Exercise – the coin toss</a></span></li></ul></li><li><span><a href="#Third-party-modules" data-toc-modified-id="Third-party-modules-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Third party modules</a></span></li><li><span><a href="#Writing-your-own-functions" data-toc-modified-id="Writing-your-own-functions-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>Writing your own functions</a></span></li><li><span><a href="#Arguments" data-toc-modified-id="Arguments-6.5"><span class="toc-item-num">6.5&nbsp;&nbsp;</span>Arguments</a></span><ul class="toc-item"><li><span><a href="#Exercise-–-truth-teller-function" data-toc-modified-id="Exercise-–-truth-teller-function-6.5.1"><span class="toc-item-num">6.5.1&nbsp;&nbsp;</span>Exercise – truth-teller function</a></span></li></ul></li><li><span><a href="#(Optional)-Styling-conventions-writing-functions" data-toc-modified-id="(Optional)-Styling-conventions-writing-functions-6.6"><span class="toc-item-num">6.6&nbsp;&nbsp;</span>(Optional) Styling conventions writing functions</a></span></li><li><span><a href="#The-return-statement" data-toc-modified-id="The-return-statement-6.7"><span class="toc-item-num">6.7&nbsp;&nbsp;</span>The <code>return</code> statement</a></span></li><li><span><a href="#Exercise-–-the-currency-converter" data-toc-modified-id="Exercise-–-the-currency-converter-6.8"><span class="toc-item-num">6.8&nbsp;&nbsp;</span>Exercise – the currency converter</a></span></li><li><span><a href="#Bulletpoints" data-toc-modified-id="Bulletpoints-6.9"><span class="toc-item-num">6.9&nbsp;&nbsp;</span>Bulletpoints</a></span></li></ul></li><li><span><a href="#Local-and-global-scopes" data-toc-modified-id="Local-and-global-scopes-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Local and global scopes</a></span><ul class="toc-item"><li><span><a href="#Global-code-cannot-use-local-variables" data-toc-modified-id="Global-code-cannot-use-local-variables-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Global code cannot use local variables</a></span></li><li><span><a href="#Global-variables-can-be-used-in-local-scopes" data-toc-modified-id="Global-variables-can-be-used-in-local-scopes-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Global variables can be used in local scopes</a></span></li><li><span><a href="#Local-scopes-can't-use-variables-in-other-local-scopes" data-toc-modified-id="Local-scopes-can't-use-variables-in-other-local-scopes-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>Local scopes can't use variables in other local scopes</a></span></li><li><span><a href="#Exercise-–-why-won't-the-code-work?" data-toc-modified-id="Exercise-–-why-won't-the-code-work?-7.4"><span class="toc-item-num">7.4&nbsp;&nbsp;</span>Exercise – why won't the code work?</a></span></li></ul></li><li><span><a href="#Object-orientation-and-Methods" data-toc-modified-id="Object-orientation-and-Methods-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Object orientation and Methods</a></span><ul class="toc-item"><li><span><a href="#Exercise-–-experiment-with-string-methods" data-toc-modified-id="Exercise-–-experiment-with-string-methods-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>Exercise – experiment with string methods</a></span></li></ul></li><li><span><a href="#Lists" data-toc-modified-id="Lists-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Lists</a></span><ul class="toc-item"><li><span><a href="#Definition" data-toc-modified-id="Definition-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Definition</a></span></li><li><span><a href="#List-index" data-toc-modified-id="List-index-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>List index</a></span></li><li><span><a href="#Slicing" data-toc-modified-id="Slicing-9.3"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>Slicing</a></span></li><li><span><a href="#Changing-list-values" data-toc-modified-id="Changing-list-values-9.4"><span class="toc-item-num">9.4&nbsp;&nbsp;</span>Changing list values</a></span></li><li><span><a href="#Removing-items-with-del" data-toc-modified-id="Removing-items-with-del-9.5"><span class="toc-item-num">9.5&nbsp;&nbsp;</span>Removing items with <code>del</code></a></span></li><li><span><a href="#List-methods" data-toc-modified-id="List-methods-9.6"><span class="toc-item-num">9.6&nbsp;&nbsp;</span>List methods</a></span><ul class="toc-item"><li><span><a href="#.append()" data-toc-modified-id=".append()-9.6.1"><span class="toc-item-num">9.6.1&nbsp;&nbsp;</span><code>.append()</code></a></span></li><li><span><a href="#.insert()" data-toc-modified-id=".insert()-9.6.2"><span class="toc-item-num">9.6.2&nbsp;&nbsp;</span><code>.insert()</code></a></span></li><li><span><a href="#.remove()" data-toc-modified-id=".remove()-9.6.3"><span class="toc-item-num">9.6.3&nbsp;&nbsp;</span><code>.remove()</code></a></span></li><li><span><a href="#.index()" data-toc-modified-id=".index()-9.6.4"><span class="toc-item-num">9.6.4&nbsp;&nbsp;</span><code>.index()</code></a></span></li><li><span><a href="#.sort()" data-toc-modified-id=".sort()-9.6.5"><span class="toc-item-num">9.6.5&nbsp;&nbsp;</span><code>.sort()</code></a></span><ul class="toc-item"><li><span><a href="#ASCII-Sorting" data-toc-modified-id="ASCII-Sorting-9.6.5.1"><span class="toc-item-num">9.6.5.1&nbsp;&nbsp;</span>ASCII Sorting</a></span></li></ul></li><li><span><a href="#(Optional)-Method-call-straight-into-index-brackets" data-toc-modified-id="(Optional)-Method-call-straight-into-index-brackets-9.6.6"><span class="toc-item-num">9.6.6&nbsp;&nbsp;</span>(Optional) Method call straight into index brackets</a></span></li><li><span><a href="#&quot;In-place&quot;-methods" data-toc-modified-id="&quot;In-place&quot;-methods-9.6.7"><span class="toc-item-num">9.6.7&nbsp;&nbsp;</span>"In place" methods</a></span></li></ul></li><li><span><a href="#The-built-in-function-list()" data-toc-modified-id="The-built-in-function-list()-9.7"><span class="toc-item-num">9.7&nbsp;&nbsp;</span>The built-in function <code>list()</code></a></span></li><li><span><a href="#The-in-and-not-in-operators" data-toc-modified-id="The-in-and-not-in-operators-9.8"><span class="toc-item-num">9.8&nbsp;&nbsp;</span>The <code>in</code> and <code>not in</code> operators</a></span></li><li><span><a href="#Similarities-between-lists-and-strings" data-toc-modified-id="Similarities-between-lists-and-strings-9.9"><span class="toc-item-num">9.9&nbsp;&nbsp;</span>Similarities between lists and strings</a></span><ul class="toc-item"><li><span><a href="#The-split()-method" data-toc-modified-id="The-split()-method-9.9.1"><span class="toc-item-num">9.9.1&nbsp;&nbsp;</span>The <code>split()</code> method</a></span></li></ul></li><li><span><a href="#Exercise-–-Build-your-own-list-function,-part-1" data-toc-modified-id="Exercise-–-Build-your-own-list-function,-part-1-9.10"><span class="toc-item-num">9.10&nbsp;&nbsp;</span>Exercise – Build your own list function, part 1</a></span></li></ul></li><li><span><a href="#Loops" data-toc-modified-id="Loops-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Loops</a></span><ul class="toc-item"><li><span><a href="#while-loops" data-toc-modified-id="while-loops-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span><code>while</code>-loops</a></span><ul class="toc-item"><li><span><a href="#CAUTION:-Infinite-while-loops" data-toc-modified-id="CAUTION:-Infinite-while-loops-10.1.1"><span class="toc-item-num">10.1.1&nbsp;&nbsp;</span>CAUTION: Infinite <code>while</code>-loops</a></span></li><li><span><a href="#The-break-statement" data-toc-modified-id="The-break-statement-10.1.2"><span class="toc-item-num">10.1.2&nbsp;&nbsp;</span>The <code>break</code> statement</a></span></li><li><span><a href="#Exercise-–-Build-your-own-list-function,-part-2" data-toc-modified-id="Exercise-–-Build-your-own-list-function,-part-2-10.1.3"><span class="toc-item-num">10.1.3&nbsp;&nbsp;</span>Exercise – Build your own list function, part 2</a></span></li></ul></li><li><span><a href="#for-loops" data-toc-modified-id="for-loops-10.2"><span class="toc-item-num">10.2&nbsp;&nbsp;</span><code>for</code>-loops</a></span><ul class="toc-item"><li><span><a href="#for-loop-with-the-range()-function" data-toc-modified-id="for-loop-with-the-range()-function-10.2.1"><span class="toc-item-num">10.2.1&nbsp;&nbsp;</span><code>for</code>-loop with the <code>range()</code> function</a></span></li><li><span><a href="#The-continue-statement" data-toc-modified-id="The-continue-statement-10.2.2"><span class="toc-item-num">10.2.2&nbsp;&nbsp;</span>The <code>continue</code> statement</a></span><ul class="toc-item"><li><span><a href="#Exercise-–-Build-your-own-list-function,-part-3" data-toc-modified-id="Exercise-–-Build-your-own-list-function,-part-3-10.2.2.1"><span class="toc-item-num">10.2.2.1&nbsp;&nbsp;</span>Exercise – Build your own list function, part 3</a></span></li></ul></li><li><span><a href="#for-loop-without-range()" data-toc-modified-id="for-loop-without-range()-10.2.3"><span class="toc-item-num">10.2.3&nbsp;&nbsp;</span><code>for</code>-loop without <code>range()</code></a></span></li><li><span><a href="#for-loops-–-with-or-without-range()?" data-toc-modified-id="for-loops-–-with-or-without-range()?-10.2.4"><span class="toc-item-num">10.2.4&nbsp;&nbsp;</span><code>for</code>-loops – with or without <code>range()</code>?</a></span></li></ul></li></ul></li><li><span><a href="#Mutable-and-immutable-objects" data-toc-modified-id="Mutable-and-immutable-objects-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Mutable and immutable objects</a></span><ul class="toc-item"><li><span><a href="#Variables'-references-to-values" data-toc-modified-id="Variables'-references-to-values-11.1"><span class="toc-item-num">11.1&nbsp;&nbsp;</span>Variables' references to values</a></span></li><li><span><a href="#Mutable-lists-in-local-scopes" data-toc-modified-id="Mutable-lists-in-local-scopes-11.2"><span class="toc-item-num">11.2&nbsp;&nbsp;</span>Mutable lists in local scopes</a></span><ul class="toc-item"><li><span><a href="#Exercise-–-why-doesn't-the-variable-change?" data-toc-modified-id="Exercise-–-why-doesn't-the-variable-change?-11.2.1"><span class="toc-item-num">11.2.1&nbsp;&nbsp;</span>Exercise – why doesn't the variable change?</a></span></li></ul></li><li><span><a href="#How-to-copy-mutable-objects-then?" data-toc-modified-id="How-to-copy-mutable-objects-then?-11.3"><span class="toc-item-num">11.3&nbsp;&nbsp;</span>How to copy mutable objects then?</a></span></li></ul></li><li><span><a href="#Tuples" data-toc-modified-id="Tuples-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Tuples</a></span></li><li><span><a href="#Dictionaries" data-toc-modified-id="Dictionaries-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Dictionaries</a></span><ul class="toc-item"><li><span><a href="#Definitions" data-toc-modified-id="Definitions-13.1"><span class="toc-item-num">13.1&nbsp;&nbsp;</span>Definitions</a></span></li><li><span><a href="#Looping-over-a-dictionary" data-toc-modified-id="Looping-over-a-dictionary-13.2"><span class="toc-item-num">13.2&nbsp;&nbsp;</span>Looping over a dictionary</a></span><ul class="toc-item"><li><span><a href="#Exercise-–-the-cheapest-country,-part-1" data-toc-modified-id="Exercise-–-the-cheapest-country,-part-1-13.2.1"><span class="toc-item-num">13.2.1&nbsp;&nbsp;</span>Exercise – the cheapest country, part 1</a></span></li></ul></li><li><span><a href="#Dictionary-methods-.get()-and-.setdefault()" data-toc-modified-id="Dictionary-methods-.get()-and-.setdefault()-13.3"><span class="toc-item-num">13.3&nbsp;&nbsp;</span>Dictionary methods <code>.get()</code> and <code>.setdefault()</code></a></span><ul class="toc-item"><li><span><a href="#.get()" data-toc-modified-id=".get()-13.3.1"><span class="toc-item-num">13.3.1&nbsp;&nbsp;</span><code>.get()</code></a></span></li><li><span><a href="#.setdefault()" data-toc-modified-id=".setdefault()-13.3.2"><span class="toc-item-num">13.3.2&nbsp;&nbsp;</span><code>.setdefault()</code></a></span></li></ul></li></ul></li></ul></div>

**Introduction**

Python is a programming language. "Language" is a pretty good analogy since python, just like, say, French, consists of some basic foundations. Before learning French, it may be a good idea to first learn some vocabulary and the basics of its grammar. The same is true when trying to learn a programming language like Python. Learn some basic phraces, vocabulary and concepts to be able to get around. To be able to experiment with it! Here, we will therefore start to look at the basic stuff in Python. 

The analogy of learning a language also reflects another important aspect. Learning programming, just as learning a language, from scratch requires time and practice. This notebook will (hopefully) give you the foundation to stand on and enough guidance to start experimenting. But to fully learn Python, you will need to invest time.

**Words of wisdom**

You don't need to be a professional programmer to solve some problems. Often, some simple Python code will do the trick. Going through this notebook, you'll probobaly (hopefully) find it easy to start experimenting on your own. It isn't learning rocket science, and it isn't learning math. 

While learning, you will find a lot of moments similar to "If A is the same as B, and C is the same as B. Then C must be the same as A". You will most certainly think "I have no idea what's going on right now", and a lot of "Aha!" It is, simply put, a lot of fun!

Going through this notebook, you might think there is a little to much emphasis on definitions of various Python concepts. But this is so that when you google stuff to find out why code you wrote didn't work, you'll be familiar with [Python terminology](https://www.w3schools.com/python/python_ref_glossary.asp). One aim with this notebook is to be a reference to return to if you need a quick update on a particular subject.


**Working in a Jupyter Notebook**

Using a notebook for learning is a good way to go, since it is really easy to experiment with code. I encourage you to try out the concepts described below while reading through this notebook. Here is a Jupyter Notebook cheat-sheet for hotkeys to keep in mind working through this course:

- The keys `A` and `B` creates new cells in your notebook. `A` creates a cell above the cell currently selected, and `B` creates one below. Each newly created cell is by default a code cell
- `M` sets a cell into a markdown (text input) cell
- `Y` sets a cell into a code input cell
- <kbd>Shift ⇧</kbd>+<kbd>Enter ↵</kbd> runs a cell, showing you the output of your code (or markdown)
- `D,D` (that is, the `D` key typed twice swiftly) will remove the selected cell
- `Z` will undo deleted cells (note that this won't work if you're editing within a cell)


Don't hesitate to add some extra cells and try out the things you read about. That's the best way to learn!

**About this course (full disclosure)**

This notebook's content has been fully created by me – Johan Ekman. I am working full time as a data journalist at one of Sweden's biggest news papers, and coding in Python is one of my main tools. But I don't consider myself a professional programmer. This notebook is based on my knowledge of the language, and there may be some explanation that is not 100 per cent accurate. If you spot any errors or misleading explanations, please let me know at johan.h.ekman@gmail.com.

Also, a big inspiration was Al Sweigart's course [Automate the boring stuff with Python](https://automatetheboringstuff.com/). I highly recommend it!

---

## Values

The most basic structures in Python are values. All programming aims to do something with some values. There are five basic value types to keep in mind going foreward:

- Integers
- Floating points (i.e floats)
- Strings
- Booleans
- Nonetype (or just the `None` value)

### Integers

Integers are just plain numbers:

In [2]:
10

10

We can always check what type of value we have with the `type()` function (more on functions in chapter 6):

In [3]:
type(10)

int

`int` for integer!

### Floats

In [4]:
10.5 # float

10.5

In [5]:
type(10.5)

float

Floats is simply a decimal number.

### String values

In [6]:
"Hello world!"

'Hello world!'

In [7]:
type("Hello world!")

str

String values can be typed with either single quotation marks `''`, or double `""`:

In [4]:
type('Hello world!')

str

String values can be huge, and contain many many different types of characters. If you want to have a long string value, you can pass three quotation marks `"""` on each side of the text. Within those, you can do line breaks etc:

In [7]:
"""Hello everyone!

I am very happy that you are trying out this course.
Also, this is a long string with line breaks.

Thanks!

"""

'Hello everyone!\n\nI am very happy that you are trying out this course.\nAlso, this is a long string with line breaks.\n\nThanks!\n\n'

In the output above, you see the character `\n` – this is just the line break symbol. If we use the `print()` function (we will go through functions later in the course, so don't worry about what it is or does), we will get the string value as we typed it:

In [9]:
print("""Hello everyone!

I am very happy that you are trying out this course.
Also, this is a long string with line breaks.

Thanks!
""")

Hello everyone!

I am very happy that you are trying out this course.
Also, this is a long string with line breaks.

Thanks!



### Boolean values

Booleans indicates "truthiness". Simply if something is `True` or `False`.

In [8]:
True

True

In [10]:
False

False

In [9]:
type(True)

bool

Please note that Python is a literal programming language, the syntax is important. The value `False` is spelled like so, with a capital `F`. Spelling it `false` will produce an error:

In [13]:
False

False

In [14]:
false

NameError: name 'false' is not defined

### The None value

In programming, there are also values to indicate non-values, or "nothingness". In Python, the most important one is the `None` value, or the `NoneType`.

In [1]:
None

Please note that running above cell produce no output. That is because this value indicates no input. There is simply nothing to return from a non-value.

The reason why such a valuetype is important is rather abstract. Let's just say that it is sometimes crucial in programming to be able to signal that nothing exists, or has happend in a running program.

In [18]:
type(None)

NoneType

---

## Expressions and operators

In Python, code is read by the _Python interpreter_. This is, basically, your computer reading and executing your code.

The most basic form of "instruction" you can give your computer – you can give the interpreter – is **expressions**. Expressions always evaluates, they always reduce, into a single value. This means that giving the interpreter a single value is an expression:

In [2]:
3 # this is an expression

3

But we can also let values interact in expressions, using **operators**. The most basic ones are the arithmetic operators (basically, math operations). For example:

In [3]:
1 + 1

2

In the cell above, we have two integer values that we add together through the _addition operator_ `+`. Here is another one, the subtraction operator, `-`:

In [20]:
1235 - 332

903

As you can see, we get an answer to the expression when we run the code. In this case, the integer 903. In Python, we say that the expression `1235 - 332` _returns_ the value 903.

More examples of operators:

In [22]:
5 * 3 # multiplication

15

In [23]:
123 / 7 # division

17.571428571428573

The division operator always returns a float value. Even if the result is even:

In [82]:
9 / 3

3.0

(Above, you see examples of **comments** in Python code. Everything that follows the `#` sign will be completely ignored by the interpreter. This is how you write comments in your code – to explain stuff without ruining your output! But it is also used to just exclude parts in your code for whatever reason)

We can evaluate longer expressions as well, containing more values:

In [4]:
2 + 4 + 3 + 41

50

And we can also mix them:

In [5]:
2 + 4 - 12

-6

### Order of operations

In Python, code is read by the interpreter in a specific manner. Before the code is run, the interpreter reads the code. It starts at the top of the code to the left, and then reads line by line to the right – one line at the time. But it will then run the code in a specific order depending on certain factors. For example, some operators take precendence over others. Take this example:

In [6]:
1 + 3 * 5

16

Some of you maybe expected the answer 20 (1 plus 3 equals 4, 4 times 5 equals 20). But since the multiplication operator takes precendence, the interpreter returns the value 16.

Above, the code is read from left to right. The python interpreter sees the operators and then reads the operations in the expression a specific order. This is called the _order of operations_. This order is:

1. Paranthesis
2. Multiplication/division
3. addition/subtraction

For example:

In [7]:
(1 + 3) * 5

20

Here, the interpreter reads the code, registeres the operators `()`, `+` and `*`. It then prioritises the code within the parenthesis (since code within parenthesis takes precedence), and then runs the resulting value `(1 + 3)` in the remaing operation `4 * 5`. 

**The Order of operations**

```

1. () Parenthesis
2. ** Exponant
3. *  Multiplication
4. /  Division
5. +  Addition
6. -  Subtraction

```

Note that there are a whole bunch more of operators that also take precendence above themselves and above ones. But these will suffice for now. 

#### (Optional) Deep dive into Order of Operations

Let's experiment! (Remember that you can create your own cells in this notebook and try out on your own!)

Take this expression, contains four values and three operators (`+`, `/` and `**`). If we run them as is:

In [34]:
3 + 6 / 3 ** 5

3.0246913580246915

Let us now experiment with paranthesis at various places in the expression. Try to guess what will happen before you run the code:

In [35]:
(3 + 6) / 3 ** 5

0.037037037037037035

Above, `(3 + 6)` is run first, which equals 9. Then `3 ** 5`, which equals 243. And finally, `9 / 243`

In [37]:
9 / 243

0.037037037037037035

In [39]:
3 + (6 / 3) ** 5

35.0

Here, first `(6 / 3)`, which equals 2. Then, `2 ** 5`, equals 32. And finally, `3 + 32`, which is 35.

In [42]:
((3 + 6) / 3) ** 5

243.0

Here, there are parenthesis within parenthesis, also called nested parenthesis. Remember, the Python interpreter reads  the code from left to right. So it starts reading the parenthesis with its `(` furthest to the left. 

That is, the expression `(3 + 6) / 3`. 

Then it reads the encased parenthesis first (since it takes precedence over the `/` operator), `3 + 6` which is 9. 

Now, it divides the resulting value 9 with 3, equals 3.

Finally, it exponates 3 with 5 (`3 ** 5`), which is 243.

#### Exercise – where to put the parenthesis?

Let's do a little exercise. I said in the introduction to this course that programming in Python isn't math. But here we have a small math exercise (sorry!). The goal here is to get you experimenting with the order of operations. We have this long chain of operations on values:

In [56]:
10 + 5 * 10 - 2 / 15 + 5 / 4 

61.11666666666667

With no parenthesis, this expression evaluates to ~61.12. Try to include parenthesis to **get the answer 1.5 instead**. You will find the solution in the solutions.ipynb notebook. Use these cells below to experiment your way through:

### Concatination

In Python, some operators can also be used in expressions with string values. Adding string values together by using the `+` operator is called _concatination_.

In [43]:
"Hello" + " " + "world!"

'Hello world!'

In [44]:
"H" + "ello world!"

'Hello world!'

You can add two string values together, but you cant subtract them. This will create an error:

In [45]:
"Hello world!" - "world!"

TypeError: unsupported operand type(s) for -: 'str' and 'str'

You can also use the multiplication operator on string values. This is called string replication (and is more of a curiosity than important to be honest; not widely used...)

In [46]:
"Hello world! " * 10

'Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! '

Note that in expressions with string values, order of operations is still in play:

In [47]:
"Hello world" + "!" * 10

'Hello world!!!!!!!!!!'

In [48]:
("Hello world" + "! ") * 10

'Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! '

## Variables and statements

#### Quick sidenote – the `print()` function

Below, we'll use the `print()` function. It takes any value within its parenthesis and "prints" it back to you. It is one (of many) of Python's _built-in functions_ (we will go through this thoroughly in chapter 6). In a Jupyter Notebook, this function is sort of redundant. In a notebook, the value being returned is always shown as the cell output when we run the code. For example:

In [19]:
3

3

In [20]:
print(3)

3


However, it is a function that is used ALL THE TIME in Python, mostly for checking what values are behind a certain variable when debugging code. For now, it is sufficient to know that it is a function, and that it just "prints" what ever value it is given :)

### Assigning variables

Now to another fundamental componant of Python – _variables_. 

Variables can maybe best be described as names we give to values in our code. This is done with the **assignment operator** `=`:

In [8]:
number = 3

Above, we _assign_ the name `number` to a value – the integer 3. This is called an **assignment statement** in python.

The variable name `number` is now registered in the computers memory and points to the integer value 3. So if we type `number` in our code, the value 3 will be returned!

In [51]:
number

3

In [52]:
number * 5

15

The name of a variable is saved to the computers memory, in what's called the variables **namespace**. Namespaces cannot be seperated by blank space:

In [53]:
number one = 3

SyntaxError: invalid syntax (<ipython-input-53-d7b288421347>, line 1)

We can do operations using only variables:

In [9]:
number1 = 3
number2 = 5

number1 * number2

15

As a final point on simple assignment statements. In the Python community, _readability_ is seen as a virtue. Therefore: **always name your variables in a readable and logical manner.** This is to make the code more pleasent to read and easier to understand.

In [80]:
a = 3 # not a particularly good variable name
stuff = 3 # also not very helpful
num = 3 # better!

### Variables and strings

Of course, we can also use variables when doing string concatination:

In [59]:
string1 = "Hello "
string2 = "world!"

string1 + string2

'Hello world!'

#### String formatting – inserting variables into string values

In Python, it is very common to insert variables in strings. Let's say we have a name that we would like to insert into a sentence:

In [60]:
name = "Johan"
sentence = " is a pretty nice guy!"

We could use string concatination to create a full sentence:

In [61]:
name + sentence

'Johan is a pretty nice guy!'

But there is an even cleaner way of doing it where we don't need an operator. We can use **string formatting**. To do this we need the key letter `f` just before the string quotations, like so: `f""`. This tells the interpreter that the string will be formatted with variables. To include variables, we insert them inside curly brackets `{}` within the string. Using string formatting, we can thus type: 

In [62]:
f"{name} is a pretty nice guy!"

'Johan is a pretty nice guy!'

**CAUTION!** This is a very very useful technique. But the syntax (=the structure of statements in the code) of string formatting has changed in various versions of Python. This means that above syntax won't work in older versions of Python. However, the older syntax is still acceptable in newer versions.

I won't go through the syntax in detail, just show you how the same string can be produced with string formatting in older versions of Python:

In [66]:
f"{name} is a pretty nice guy!" # present syntax

'Johan is a pretty nice guy!'

In [67]:
"{} is a pretty nice guy!".format(name) # former syntax

'Johan is a pretty nice guy!'

In [68]:
"%s is a pretty nice guy!" % name # really old syntax

'Johan is a pretty nice guy!'

However, I highly recommend the present syntax, since it is way more readable and clean.

#### (Deepdive) – Long strings, string literals and the escape character `\`

#####  More on tripple quote strings

In chapter 1, we briefly touched the subject of creating long strings with tripple quotes `"""`. In these, we tell the interpreter that _all_ characters following these quotes are part of one string value, until it finds a the enclosing set of tripple quotes. This means we can do linebreaks within the string to make it more readable since we don't want the entire string on one line. Take this example:

In [28]:
# This isn't very readable...
single_quotes = "This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. "

# ...compared to this:
tripple_quotes = """
This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 
"""

As you can see, the same string is a lot more readable using the `"""`. We should always try to make the code more readable (more on this in section 3.5), and as a general guidance: **never write lines of code that are longer than 70 characters**. The string value assigned to `single_quotes` is thus to long, and the `tripple_quotes` string value is much more readable.


However, _they are not the same string._ The reason is because we did linebreaks in the second one. The difference becomes apparent if we print the two variables:

In [13]:
print(single_quotes)

This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. 


In [14]:
print(tripple_quotes)


This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 



##### String literals and the backslash `\`

If we want a more readable code using tripple quotes, but don't want to include any linebreak characters, we can use the backslash `\` character. This is a special character that lets us escape so called **string literals**. [There are a handful that you can use](https://docs.python.org/2.0/ref/strings.html), and they help us format strings in different ways. I won't go through them all here, but we've already covered one – the newline string literal `\n`: 



In [51]:
print("Hello\nworld!") # \n means "insert newline"

Hello
world!


Also, the horisontal tab `\t`:

In [52]:
print("Hello\tworld!")

Hello	world!


The newline string literal is actually inserted in tripple quote strings every time we press <kbd>Enter ↵</kbd> within our string quotes:

In [53]:
"""
"""

'\n'

So, back to the example we had in the variable `tripple_quotes`, we actually included the newline `\n` in the string on every row:

In [54]:
tripple_quotes = """
This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 
This is a long string. 
"""

In [55]:
tripple_quotes

'\nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \n'

The `tripple_quotes` string value is actually the same as writing:

In [56]:
single_quotes_linebreaks = "\nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \n"

This means that if we were aiming to rewrite the variable `single_quotes` with `"""`, we failed, since it is a different string value:

In [59]:
single_quotes = "This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. "

In [60]:
single_quotes

'This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. '

In [62]:
single_quotes_linebreaks

'\nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \nThis is a long string. \n'

Using a comparison operator (more on these in the next chapter, they return True if values on each side are the same), we can see that they are not the same value:

In [63]:
single_quotes == single_quotes_linebreaks

False

However, we can nullify string literals by using the escape character, the backslash `\`:

In [64]:
"""\
"""

''

Using the backslash, we can still use tripple quotes, and get the same value! It is handy while working with long string values – to increase readability while at the same time tell the interpreter which linebreaks that should include newline characters. In this case, we can escape all newlines to get `tripple_quotes` and `single_quotes` to produce the same exact string value.

So, if we want Using the `\` character:

In [65]:
tripple_quotes = """\
This is a long string. \
This is a long string. \
This is a long string. \
This is a long string. \
This is a long string. \
This is a long string. \
This is a long string. \
This is a long string. \
"""

In [66]:
print(tripple_quotes)

This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. This is a long string. 


In [68]:
tripple_quotes == single_quotes # tada!

True

The mixture of tripple quotes and the `\` character is more for situations where you want one passage in the string to remain on one line, while some other parts of the same string value should be including newline characters. Take this example:

In [69]:
long_string = """
This is one long sentence, with a lot of words, \
that I still want to be kept in one long sentence; \
but since it is rather long I will need to cut it \
up to increase readability.

This, however, is a list within the string, \
and here I WANT linebreaks:

- First item
- Second item
- Third item
etc...

"""

In [70]:
print(long_string)


This is one long sentence, with a lot of words, that I still want to be kept in one long sentence; but since it is rather long I will need to cut it up to increase readability.

This, however, is a list within the string, and here I WANT linebreaks:

- First item
- Second item
- Third item
etc...




As a final point, the backslash is also called the **line continuation character**. If not used in a string, it tells the interpreter "this line of code continues on the next line"! Take this example where we concatinate a long string:

In [35]:
# This will fail
"Hello " +
"world! " +
"How " +
"are " +
"you?"

SyntaxError: invalid syntax (<ipython-input-35-e8beae0e0012>, line 2)

But if we use the line continuation character, we can make thid work:

In [36]:
"Hello " + \
"world! " + \
"How " + \
"are " + \
"you?"

'Hello world! How are you?'

##### Exercise – write a letter!

In this exercise, you will need to reformat the following text (it is a grocery list) so that it gets printed in  the correct manner. You will also need to heed of the rule to not have any line of code longer than ~70 characters. The parts enclosed within `<>` shall be replaced by whatever is instructed using variables and string formatting! 

Here's the letter with the grocery list:

In [44]:
grocery_list = "Hi <receiver>! All ingredients are necessary, \
so please don't forget any item in the list. Also, you know I love \
a little snack after dinner, so please get something you know I \
love – like <nice_treat>. Please hurry, I am starving! - Milk - \
Spinach - Strawberry jam - Spam - Whole cream - Cat food Remember \
that we have loads of credits to spend. We need to save up some \
money for our dream vacation next year. I am soooo looking forward \
to travel to <destination>. That is, if the virus ever would let us go :( Love, \
<your_name>"

In [45]:
print(grocery_list)

Hi <receiver>! All ingredients are necessary, so please don't forget any item in the list. Also, you know I love a little snack after dinner, so please get something you know I love – like <nice_treat>. Please hurry, I am starving! - Milk - Spinach - Strawberry jam - Spam - Whole cream - Cat food Remember that we have loads of credits to spend. We need to save up some money for our dream vacation next year. I am soooo looking forward to travel to <destination>. That is, if the virus ever would let us go :( Love, <your_name>


At the moment, it is on one single line. You will need to format it using these variables and string formatting:

In [46]:
receiver = ""
nice_treat = ""
destination = ""
your_name = ""

Here's how it should look:

In [48]:
# DON'T RUN THIS CELL


Hi Mom!

All ingredients are necessary, so please don't forget any item in the list. Also, you know I love a little snack after dinner, so please get something you know I love – like Ben & Jerrie's ice cream. Please hurry, I am starving!

- Milk
- Spinach
- Strawberry jam
- Spam
- Whole cream
- Cat food

Remember that we have loads of credits to spend. We need to save up some money for our dream vacation next year. I am soooo looking forward to travel to Paris. That is, if the virus ever would let us go :(

Love,

Johan



Remember that you can use string formatting on tripple quotes strings as well! The solution can be found in the solutions notebook!

### Changing variables – Operators and assignment statements

Often when coding, we want to change the values of our variables. We _overwrite_ our variable, giving it a new value. This is easily done in python:

In [67]:
number = 3 # assignment statement

In [68]:
number = number + 4 # take the variable "number" and add 4, reassign the result to the "number" variable

In [69]:
number # "number" is now 7 (3 + 4 = 7)

7

#### Augmented assignment operators

When using `=`, the python interpreter will evaluate the expression to the right of the assignment operator first. Then it will assign the returned value to the namespace written to the left of the `=` (`number`). This is how you reassign, or overwrite, your variables. 

But you can also use the assignment, AND the addition operator in one go using the addition statement `+=`. This is called an **augmented assigment operator**, it uses the operator on the variable _while also assigning the result to the variable_. Take this example:

In [70]:
number = 3

In [90]:
number += 4 # '+=' is syntax for "add the value to the right to the variable name to the left"

In [72]:
number

7

The same can be done with subtraction, multiplication and division:

In [73]:
number -= 1

In [74]:
number

6

In [75]:
number *= 5

In [76]:
number

30

In [77]:
number /= 3

In [78]:
number

10.0

### Multiple assignment statements

In Python, let's say we want to create four variables with different values. This is boring and tedious to type out:

In [10]:
one = 42
two = "Johan"
three = True
four = "elephant"

In [11]:
one

42

In [12]:
four

'elephant'

Luckilly, this can be written in one single line of code, with a single `=`. We just pass the variable names to the left of the assignment operator – seperated by commas – and the values to the right – seperated by commas – in the order we want the values assigned:

In [13]:
one, two, three, four = 42, "Johan", True, "elephant"

In [14]:
one

42

In [15]:
two

'Johan'

In [16]:
three

True

In [17]:
four

'elephant'

### (Optional) More about readability – the zen of Python

Earlier, we talked about naming variables in a logical and transparent manner. We should name our variables making it easier to understand what values they may hold. This is important – it makes your code more readable. Readability is a very important aspect of writing Python. 

The reason for this is quite simple: **as a person working with coding, you will read a lot of code.** Returning to old projects for example, what code does what and where in your program? If you learn early on to make your code more readable, you will save eons of time later on!

The Python community will sometimes refer to what is called [_the zen of python_](https://www.python.org/dev/peps/pep-0020/). This is the general "rules" that should guide you when you code. These are the first seven lines in it:

```
Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
```

This is a bit abstract, but it is words that is good to keep in mind going forward. There are many concrete ways to write more readable code. For example, use white space (blank space) in your expressions:

In [86]:
2 + 2 # zen-like

4

In [87]:
2+2 # this is less readable – therefore, don't! :)

4

Or, in your assignment statement:

In [88]:
num=2 # don't
num = 2 # do!

For more on how to write readable python code, [check out this link!](https://docs.python-guide.org/writing/style/)

### Exercise – string concatination and variables

In this exercise, I want you to assign these seven string values to one variable each:
- `"was"`
- `"the"`
- `"on"`
- `"cat"`
- `"mat"`
- `"inside"`
- `"hat"`

Using these variables, use string concatination to produce these three sentences:
1. "cat was inside the hat on the mat"
2. "hat was inside the cat on the mat"
3. "mat was inside the hat on the cat"

You can add blank spaces to the strings if you'd like.

When assigning your variables, try to use a multiple assignment statement.

The solutions is found in the solutions notebook (there is more than one!

---

## Comparing values

### Comparison operators

In section 1, we briefly covered the boolean values. In code, we often want to check if something is true or false. 

Let's say we want to write a program that functions as an alarm that lets us know if our workday is over. The program would then have to check the time, and then see if the present time is past five o'clock. If so, it alarms us that the work day is over. If not, it does nothing. Lets put this down in writing:

Program workflow:
```
1. Check time
2. See if time is past 17.00 (either true/false)
3. If true -> alarm us! If false -> do nothing
4. Terminate program
```
In such a program, we need an operator that can compare values. In our case, compare present time with the end of our workday (17.00). This is when we use a **comparison operator**! These are:

```
COMPARISON OPERATORS

    ==   Equal to
    !=   Not equal to
    <    Less than
    >    Greater than
    <=   Less than or equal to
    >=   Greater than or equal to
```
Expressions with comparison operators always return a boolean value:

In [99]:
3 == 3 # 3 is equal to 3

True

In [100]:
3 == 4 # 3 is not equal to 4

False

In [103]:
3 <= 3 # 3 is less than or equal to 3

True

In [101]:
3 <= 4 # 3 is less than or equal to 4

True

In [18]:
3 >= 4 # 3 is not greater than or equal to 4

False

Note that comparison operators _checks for value types_. This means that:

In [108]:
3 == "3"

False

...since `3` is an integer and `"3"` is a string. However, integers and floats can be equal to eachother:

In [109]:
3.0 == 3

True

Comparison operators can, of course, also be used to check variables:

In [105]:
my_name = "Johan"

In [106]:
my_name == 'Pete'

False

Above, please note that the first cell `my_name = "Johan"` has _one_ assignment operator. This is an assignment statement where we create our variable. The second cell has _two_ assignment operators – hence, a comparison operator.

### Boolean operators

There are also three boolean operators: `and`, `or` and `not`. These let's us evaluate two or more booleans into one boolean value. Since we often need to take more things into consideration than something _only_ being true or false, these operators are essential when coding. Programs and scripts often need to handle ambigious situations, making them unambigious :)

Consider our earlier example, our workday alarm program. Let's say the workday starts at 9.00 in the morning and we want to check if the present time is during work hours or not. If so, we can use a boolean operator: is the present time after 09.00 _AND_ before 17.00?

#### The `and` operator

Let's first look at the `and` operator. The `and` operator returns `False` if the two expressions to its left and to its right doesn't _both_ evaluate to True:

In [112]:
True and False

False

In [113]:
True and True

True

In [118]:
False and False

False

In [126]:
1 == 1 and 4 == 4

True

In [127]:
1 == 2 and 4 == 4

False

In [128]:
1 == 2 and 4 == 5

False

In other words, the `and` operator will always evaluate to `False` if not both expressions are `True`.

#### The `or` operator

If we instead use the `or` operator, it will return `True` if either expressions are true:

In [120]:
True or False

True

In [122]:
1 == 2 or 4 == 4

True

In [123]:
False or False

False

In [124]:
1 == 2 or 4 == 5

False

#### The `not` operator

The `not` operator only evalueates on one boolean value, and it always returns its opposite:

In [129]:
not True

False

In [130]:
not False

True

#### Boolean operators – examples

This may look like very abstract concepts, but it makes way more sense if we use them together with variables. Let create some:

In [131]:
name = "Johan"
nationality = "Swedish"

Using it together with the `and` operator:

In [132]:
name == "Johan" and nationality == "Swedish"

True

In [133]:
name == "Johan" and nationality == "Finish"

False

The `or` operator:

In [135]:
name == "Johan" or nationality == "American"

True

The `not` operator:

In [137]:
not name == "Pete"

True

If we return to our alarm program:

In [138]:
presentTime = 12.15

In [139]:
presentTime < 17.00 and presentTime > 9.00

True

In [140]:
presentTime = 17.15

In [141]:
presentTime < 17.00 and presentTime > 9.00

False

### Exercise – insert the correct operators

In this exercise, I want you to uncomment the code. Then, replace the `?` characters with the correct operators so that the `print()` function is executed. In other words, you'll need to change operators so that all comparisons are evaluated to `True`.

In [1]:
number = 12

In [ ]:
#if number ? 15:
#    print("Correct!")

In [2]:
#if number ? 5 and number ? -5:
#    print("Correct!")

In [ ]:
#if number ? 150 or number ? 25:
#    print("Correct!")

In [3]:
#if number ? 12:
#    print("Correct!")

In [71]:
#if number ? "Hello world!":
#    print("Correct!")

## Flow Control Statements

As has been discussed above, we often want to take various context into consideration when coding. "If an expression is true, do something...". We want to have control of our program's progress, how it "flows". In Python, we can use comparison operators in **flow control statements**: these are: 
- `if` 
- `elif`
- `else`

\*\* Going forward, remember that **what you type (the syntax) is important!** Be sure that you write these statements exactly as described. Otherwise, you will get an error and your code won't work. \*\*

### The `if`-statement

Flow control statements make your code follow a certain logic. The `if`-statement consists of the keyword `if`, followed by a **condition** (=just another word for an expression, but connected to a flow control statement), and ended with a colon `:`. 

If the if-statement's condition evaluates to false, the interpreter skips code. Have a look at this:

In [21]:
name = "Johan"

In [22]:
if name != "Johan":
    print("Hi Johan!") # name != "Johan" is false. This line of code will be skipped

Code that are indented at the same level is called **a block of code**. Indentations are therefore very important in Python, since it tells our computer what code that is to be considered grouped together. The `print()` function is one block of code within our if-statement (even though it's just one line in this example).

If the condition in the if-statement is evaluated to `False`, the indented block (containing `print("Hi Johan!")`) will be skipped and not be executed. If the condition is `True`, then the indented code will execute:

In [193]:
if name == "Johan":
    print("Hi Johan!") # The condition name == "Johan" is true! Hence, this line of code will be executed

Hi Johan!


Another example:

In [167]:
age = 35

In [168]:
if age > 30:
    print("Whoa! Not that young any longer, buddy!") # True! This will be executed

Whoa! Not that young any longer, buddy!


In [169]:
if age < 30:
    print("Whoa! Not that young any longer, buddy!") # This will be skipped since 35 is more than 30

In [162]:
youngAge = 25

In [165]:
if youngAge < 30:
    print("You, sir, are in your prime!")

You, sir, are in your prime!


We can also use boolean operators in flow control statements, like the `and` operator:

In [174]:
if youngAge < 30 and youngAge >= 20:
    print("You are in your twenties! Congratulations!")

You are in your twenties! Congratulations!


### The `else`-statement

But what about if we also want to cover situations where the if-statement is false? Then we use the `else`-statement:

In [166]:
age = 35

In [171]:
if age < 30:
    print("Hello young sir!")
else:
    print("Oldie but goldie!")

Oldie but goldie!


So "If an expression is true, do something... Otherwise, do this other thing..." An `else`-statement contains of the `else` keyword followed by a colon, `:`.

An else-statment does only work if it follows an if-statement. Only writing an else-statment will produce an error: 

In [172]:
else:
    print("Hello world!")

SyntaxError: invalid syntax (<ipython-input-172-eb2670b32139>, line 1)

Note that the else-statement doesn't contain a condition. Since the code block beneath the else-statment is to be executed in all situations where an it-statement is false, a condition isn't needed. 

Our workday alarm program, but with an if/else-statement:

In [194]:
present_time = 12.15

In [195]:
if present_time < 17.00 and presentTime > 9.00:
    print("You should be working!")
else:
    print("No work!!")

You should be working!


### The `elif`-statement

In many situations we want to explicitly cover more scenarios than just those covered in our if- and else-statements. This is where we can create `elif`-statements:

In [253]:
age = 16

In [254]:
if age >= 30:
    print("You are not very young any longer, I'm afraid.") # 16 is lower than 30, so this is skipped
elif age >= 20 and age < 30:
    print("You are in your twenties!") # 'age' is not between 20 and 29, this block is also skipped
elif age < 20 and age >= 13:
    print("A teenager!") # Bingo! This is executed
else:
    print("You are very, very young!")

A teenager!


As you can see in the code cell above, we can use more than one elif-statement. You can put in as many as you like! But remember, just like the else-statement, the elif-statement can only be used after an if-statement. Otherwise, an error will be produced:

In [196]:
elif age >= 20 and age < 30:
    print("You are in your twenties!")

SyntaxError: invalid syntax (<ipython-input-196-5150a1770b0d>, line 1)

Here is the hierarchy of these three flow control statement:

1. if-statement goes first
2. elif-statements (as many as you like!) comes second
3. And finally, the else-statement

### (Optional) "Truthy" and "Falsy" values

Like covered above if-statements need an expression (called a condition) to evaluate to true or false to run. But in Python, all values are actually either truthy or falsy. This means that a single value following the if-keyword will also work:

In [197]:
if 3:
    print("Works!")

Works!


In [202]:
if 3.5:
    print("Works!")

Works!


In [211]:
if 0:
    print("This won't be printed...")

In [212]:
if 0.0:
    print("This won't be printed...")

All number values, that is both integers and floats, above 0 is considered "truthy" values in Python. 0 and 0.0 is "falsy". In string values, all empty strings `""` are considered falsy, all other string values are truthy:

In [208]:
if "a string value":
    print("Works!")

Works!


In [210]:
if "":
    print("This won't be printed...")

Considering we should always strive to make our code more readable, above examples should be avoided. Instead we should write an actual comparison:

In [207]:
value = "string"
if value != "":
    print("This wasn't an empty string!")

This wasn't an empty string!


We can always check values "truthiness" with the built-in function `bool()`:

In [213]:
bool(3)

True

In [214]:
bool("")

False

In [215]:
bool(0)

False

In [216]:
bool("Hello world!")

True

### Exercise – type the end of the story!

If-statements are rather useful if you're creating small text based games. Think of a Python script that runs a dungeons and dragons game, what does the player choose? How does it affekt the storyline?

In this exercise, you will write an ending to a little (silly) story. You will write it as an flow control statement. By choosing a value for the variable `item`, and by passing it to a flow control statement, this variable decides the ending of the story! Depending of the value of `item` a different ending should then be printed with a `print()` function. You write the story ending that's printed! Save this story to variable called `ending`, and then print this variable. Simple!

Remember that you can write string values with tripple quotes `"""` to make them a long string (see section 3.2 if you want to refreash your memory!). Good luck!

**The End of the Story**

```
Teddy Merrybottom was tired. He had done what had been asked of him. With him, he carried enough booty to make his entire village the most wealthy in Southern Illyria. But the journey to Doom Mountain had been exhausting, and tragic. His three best friends had all perished. 

He couldn't for the life of him understand why they wanted to swim while in full armor. Granted, their fight with the dragon Grymf had been a fantastic, and surprising success – worthy of great celebration. But getting completely planked on honey beer, and then go swimming with breast plates? It was a bummer. Well, it was also sad, since, you know, they died.

Even more disapointing was that the only one in Teddy's company that hadn't joined the party – and died – was Gary. And Garry was an idiot. And now, even though their three best friends was dead, Gary just kept complaining about his arthritis and how his knees hurt. This also meant that Teddy was taking care of all their stuff.

Fortunatly, they were just about a hill away from their village. Teddy looked forward to being in front of his fire place, being rich and all that. But most of all, not having to spend any more time with Gary.

– What is that!? Gary suddenly gasped

– Where? Teddy replied, reaching for his sword hilt

They were walking on a field right next to the edge of Hillside Forrest, and inbetween the trees, Teddy saw the contours of something vile. It was a Vampwolfosauros. A howling, bloodsucking lizard beast. It had seen them, and rushed towards them in a rage, trampling trees in its path.

Teddy, struck by an instant adrenaline rush, drew his sword. He turned around to get his shield from the horse carriage. But in his exitement, he stumbled, and grabbed the only thing close to help him not loosing his footing – the horse strings. 

This pulled the horse in the direction towards the approaching monster, and, of course, it panicked and reared. It did so right next to a small boulder with a sharp edge, which cut the horse's leg. The horse, therefore, also lost its footing, tumbling over Teddy. In the chaos, the cart crashed to its side. 

Suddenly, Teddy found himself stuck in a pile of gold, jewels, weapons, and horse. And the Vampwolfosauros was just moments away. It was sure to rape and kill them all! Vampwolfosauroses was known to be not only predators, but sexual predators.

It was now all in the hands of Gary. Teddy and Gary both realised this, and they both felt terror. Gary's only chance was that Teddy would throw him something for their mutual protection against the massive, raging beast. But what?

Teddy looked around. He saw four magical items lying next to him: 
- the Ice Jewel
- the Ancient Staff of Pharts 
- the book "The World's 10 Worst Poems"
- the Bear Spear (a magical spear shaped like a bear)

He realised that chances were slim with either, since Gary was an blidgering moron. But he reached out and grabbed his item of choice and threw it to Gary, screaming "Come on you fool, save us!!"
```

In [ ]:
item = "" # <- which item does Teddy choose?

In [11]:
# write a flow control statement, containing at least one each of an if-, elif- and else-statement
# this flow control statement should decide the end of the story, depending on which item Gary's given
# Good luck!

## Functions

A function in Python is perhaps best described as a miniprogram within our code. It is block of code that is assigned to a namespace. We can then use and reuse the function, without having to rewrite all the code within it! Above, we have briefly touched on the subject of Pythons built-in functions.

Let's say we want to count the number of characters in a string value. We can write code to do that for us. (In this example, don't get stuck on the code itself, it includes concepts we still havn't covered)

In [272]:
string_value = "Johan"

In [273]:
for index,char in enumerate(string_value):
    num = index + 1 # again, don't get stuck in this code. We will cover it later :)

In [274]:
num

5

Above, we have a small snippet of code that helps us calculate how many characters there are in a string value. But let's say we want to use this code snippet in many different places in our program. It would not be very convenient to write this code over and over again. This is a great time to use a function instead. Fortunately, there is a built-in function that helps us with excactly that – the `len()` function:

In [275]:
len("Johan")

5

The `len()` function returns the number of items in a python container object. So, if given a string, the `len()` function will return the number of characters in the string.

A function always have a name, in this case "len", and can be used by typing `()` directly after the function name.

Now some important Python vocabulary: Above, we give the function the string value "Johan" by writing it within its parenthesis. This is called **the function's argument**, and if we give a function an argument, we say that **we pass an argument to a function**. When we pass an argument to a function's parenthesis, we say that we **call the function** (or that it is a **function call**), but we can also say that we **invoke the function**. As you can see, there are often many names to the same concepts in Python. 

(These phrases will be used throughout this notebook, but if you are uncertain of the meaning of a term used, first try finding the explanation wihtin this notebook using <kbd>⌃ Control</kbd>+<kbd>F</kbd>, OR Google it! Googling programming concepts is a great way to learn!)

Since the `len()` function only works on containers, it will give us an error if we pass it something other than a container – like an integer:

In [276]:
len(5)

TypeError: object of type 'int' has no len()

In Jupyter, we can type <kbd>⇧ Shift</kbd>+<kbd>⇥ Tab</kbd> when our marker is within a function's parenthesis to see information about the function!

In [281]:
len("") # <- try putting your marker within the double quotes in the parenthesis and tapping shift+tab

(The information you see when tapping <kbd>⇧ Shift</kbd>+<kbd>⇥ Tab</kbd> is called the function's **docstring**)

### Built-in Functions

In previous chapters in this notebook, we have used some built-in functions already. For example:

In [282]:
type(42) # checking an objects datatype

int

In [226]:
print("Hello world!") # tells the interpretor to print the function's argument

Hello world!


We can also convert values into other datatypes (remember that you can always check the functions' docstring pressing <kbd>⇧ Shift</kbd>+<kbd>⇥ Tab</kbd> when your marker is within the functions' parenthesis):

In [227]:
str(4) # returns passed argument as a string

'4'

In [228]:
int(5.0) # returns passed argument as an integer

5

In [230]:
int("5")

5

In [233]:
float(10) # returns passed argument as a float

10.0

In [234]:
float("10")

10.0

There are many more of these built-in functions. Every time you use python code, these will work from the getgo. But there are many many more functions that come prepackaged within the standard Python code package, but that don't work immediatly. They have to be imported from various modules.

### The standard library and modules

When you use a freshly installed version of Python, it comes with a set of built-in functions. But it also comes with a variety of "libraries" of code that can be easly accessed and used in your code. This is called **the standard library**. To get access to these, we just use the `import` statement. The libraries of code we import are called **modules**, or **packages**. Let's import the `random` modul:

In [73]:
import random

After we have imported, we can use a range of functions in this library by typing a dot `.` directly after the module name. In Jupyter, there is a really neat trick to see which functions are included. After having typed `random.`, press the <kbd>⇥ Tab</kbd> key to get a list of available functions:

In [74]:
# replace this comment with the code "random." and then place your marker next to the "." and press the tab key!

In this case, we want to use the function called `randint()` from the random module. This function takes two arguments: one starting point number value, and one end point number value, and returns a random number inbetween:

In [75]:
random.randint(1, 10)

2

In [77]:
random.randint(-2446, 10645)

-1825

That is how you use imported modules and their functions!

We can also specifiy which method we want from the random module in our import statement by using the `from` keyword:

In [78]:
from random import randint # from the 'random' module/package, import the function 'randint'

In [79]:
randint(1, 10) # now, we don't need to specify module, since we directly imported the function itself!

3

Another cool module to import is the `os` module. It lets us explore the files on our computer! Let's import it:

In [80]:
import os

We can use the `listdir()` function to get us a list of all files in the directory (=folder) this notebook is located within:

In [81]:
os.listdir()

['python_intro_eng.ipynb',
 '.DS_Store',
 'LICENSE',
 'course_material',
 'Pipfile',
 'solutions.ipynb',
 '.gitignore',
 '.ipynb_checkpoints',
 '.git',
 'Pipfile.lock']

In our import statement, we can also just import all functions and methods within a module at the same time with the from keyword. This is done using the `*`

In [244]:
from os import *

This means we imported ALL functions within the `os` module. It is the same as just typing `import os`, but now we don't need to specify the module name before using its functions. 

HOWEVER! This is not recommended. It makes our code less readable. In Python, you should always aim to make your code transparent.

#### Exercise – the coin toss

The random module's function `randint` can be used to produce random number. In this exercise, you shall try to build a small script that takes a random number, and depending on the number, either "Heads!" or "Tails!" is printed by the `print()` function. This will require you to use variables, the `random.randint()` function, and flow control statements.

Remember to import the random module! The solution is found in the solutions notebook.

Good luck!

### Third party modules

One huge advantage in learning Python is its flourishing community. Many, many, many programmers contribute to the Python language, often by supplying third party modules. This is modules that is not part of the standard library. They need to be downloaded before you can import and use their functions. This is normally done by using the `pip` Python library installer. This is not covered in this notebook, but an extensive guide [can be found here.](https://packaging.python.org/tutorials/installing-packages/)

If you are using Jupyter through the Anaconda software, this means you acctually have a number of such third party modules already installed on your computer. You can see all your available libraries by using the built-in function `help()`:

In [ ]:
help('modules')

In the list you can find libraries such as `pandas`, `numpy` and `matplotlib` (to name a few) – all third party modules! All the packages in the list can be imported using the `import` statement.

### Writing your own functions

As was explained briefly in the beginning of this chapter, a function is like a miniprogram within our code. This miniprogram has a name that we can call (or invoke) to reuse the code within the function.

In the above sections, we have learned about built-in and imported functions. But we can easally build our own! Let's build a function that greets us hello!

In [295]:
def greetings():
    print("Hello deer!")
    print("How are you?")
    print("I am well, thanks for asking!")

Running above cell will not produce an output. It is a function statement where we simply define our function. This is done by typing the keyword `def`, followed by our name of the function, followed by parenthesis, followed by a colon `:`. When you typed all that, it is time to define the functions content code. After the colon, we press the <kbd>↵  Enter</kbd> key, and the next line is automatically indented, marking that the functions code is in a new code block! The function's content is the `print()` functions that are being called. 

We can now call our function by invoking its name! (to be more concrete about the meaning of invoking, it is when you put the parenthesis next to the function's name to call it)

In [296]:
greetings()
greetings()
greetings()

Hello deer!
How are you?
I am well, thanks for asking!
Hello deer!
How are you?
I am well, thanks for asking!
Hello deer!
How are you?
I am well, thanks for asking!


Now, if we HADN'T used a function, the code for getting us the same output would be:

In [290]:
print("Hello deer!")
print("How are you?")
print("I am well, thanks for asking!")
print("Hello deer!")
print("How are you?")
print("I am well, thanks for asking!")
print("Hello deer!")
print("How are you?")
print("I am well, thanks for asking!")

Hello deer!
How are you?
I am well, thanks for asking!
Hello deer!
How are you?
I am well, thanks for asking!
Hello deer!
How are you?
I am well, thanks for asking!


In Python, we want to have as little duplicated code as possible. We get shorter programs, code that is easier to read, and – perhaps most importantly – _code that is easier to edit and debugg_. 

As some of you might've spotted, there is a spelling error in above code. We've acctually not used the pleasantry "Hello dear" in our greeting. Instead we called the person we're greeting a deer. Not very nice. When using functions, this is an easy fix: we just change the code within the function's code block to:

In [291]:
def greetings():
    print("Hello dear!") # <- easy fix!
    print("How are you?")
    print("I am well, thanks for asking!")

In [293]:
greetings()
greetings()
greetings()

Hello dear!
How are you?
I am well, thanks for asking!
Hello dear!
How are you?
I am well, thanks for asking!
Hello dear!
How are you?
I am well, thanks for asking!


If we hadn't used a function, we would've had to change it in all places where the spelling error occured:

In [292]:
print("Hello dear!") # Here...
print("How are you?")
print("I am well, thanks for asking!")
print("Hello dear!") # here...
print("How are you?")
print("I am well, thanks for asking!")
print("Hello dear!") # and here
print("How are you?")
print("I am well, thanks for asking!")

Hello dear!
How are you?
I am well, thanks for asking!
Hello dear!
How are you?
I am well, thanks for asking!
Hello dear!
How are you?
I am well, thanks for asking!


As you can see, this is not very practical. And it is also easy to miss all the occurances of an error in duplicated code. So: if you can avoid it – don't duplicate code! :)

### Arguments

In [297]:
len("Johan")

5

In this `len()` function call, we pass the function an argument – the string value "Johan". When building our own functions, we can specify if arguments should to be passed to them and used within the function. In this context – when we put a variable in between the parenthesis while defining a function – this is called the function's **parameter**. Let's build on our greeting function:

In [353]:
def greetings(parameter):
    print("Hello dear " + parameter + "!") # this is string concatination. Remember?
    print("How are you?")
    print("I am well, thanks for asking!")

Arguments are information that is passed in the function call and is then used within the function's code block. Above, I've called the parameter `parameter` to make it obvious where we put it. We can, however, name the arguments to whatever we like. `parameter` is not a very readable name. Remember that we want the code to be readable, and the name `parameter` is rather generic. Let's change it:

In [354]:
def greetings(name):
    print("Hello dear " + name + "!")
    print("How are you?")
    print("I am well, thanks for asking!")

Now, when we call the argument like before, we will get an error:

In [355]:
greetings()

TypeError: greetings() missing 1 required positional argument: 'name'

When a argument is mandatory for the function call to work, it is called a **positional argument**. The error message tells us that an argument is required, and then tell us the name of the parameter missing a value. This is why it is important to name your parameters in a readable manner. If our name would just be "parameter", the error message wouldn't make any sense.

When an argument is put in the function call, this will then be used in the function's code block. Let's have a look at a few examples:

In [356]:
greetings("Johan")

Hello dear Johan!
How are you?
I am well, thanks for asking!


In [357]:
greetings("Pete")

Hello dear Pete!
How are you?
I am well, thanks for asking!


In [358]:
greetings("Hanna")

Hello dear Hanna!
How are you?
I am well, thanks for asking!


As you can see, we can pass any string we like to the function!

In [359]:
greetings("KJ&€!AEFHO&#AHIUFQO%!PJ")

Hello dear KJ&€!AEFHO&#AHIUFQO%!PJ!
How are you?
I am well, thanks for asking!


So, what is actually going on here? When we pass our string value to the function, it is assigned _within the function_ as a variable – the variable `name`. It is this variable that is called the function's parameter. We can even specify which parameter the argument should be set to in the function call, **we can name arguments in the function call**:

In [350]:
greetings(name="Johan") # the parameter is set to the argument value "Johan"

Hello dear Johan!
How are you?
I am well, thanks for asking!


Let's create a new function that just prints the function's argument:

In [351]:
def return_name(name):
    print(name)

In [352]:
return_name("Johan")

Johan


So, to recap:
- The function's **argument** is the value that is passed to the function when you call it (the string value "Johan" in the above example)
- The function's **parameter** is the variable name to which the value is assigned (the variable `name` in the above example)

You can also have more than one parameter when you define your functions. You just put more parameters within the parenthesis, while defining your function, seperated by a comma.

As an example, let's redefine our greeting function to also require a `country` parameter:

In [361]:
def greetings(name, country):
    print("Hello " + name + "! You're from " + country + ", right?")

Let's clean it up using string formatting (see section 3.2.1 if you need a refreasher!):

In [82]:
def greetings(name, country):
    print(f"Hello  {name}! You're from {country}, right?")

In [335]:
greetings("Johan", "Sweden")

Hello Johan! You're from Sweden, right?


Since we have set the function with two parameters, just giving the function one argument in the function call will now produce an error:

In [336]:
greetings("Johan")

TypeError: greetings() missing 1 required positional argument: 'country'

Remember, the order of parameters counts. If you pass positional arguments in the wrong order, it may not result in what you expected:

In [337]:
greetings("Sweden","Johan")

Hello Sweden! You're from Johan, right?


However, if we specify which argument we want to which parameter variable name, the order doesn't matter:

In [338]:
greetings(country="Sweden", name="Johan")

Hello Johan! You're from Sweden, right?


#### Exercise – truth-teller function

In this exercise, you will define your own function. This function shall have two parameters. When you call the function, it should first print the two arguments, then it should compare them. If the passed arguments are not the same, the function should print "The arguments are not the same...". If they are the same, the function should print "The arguments are the same!"

The solution can be found in the solutions notebook. Good luck!

### (Optional) Styling conventions writing functions

Here's a (kind of) quick style guide when you're defining functions. Let's take the earlier example:

In [363]:
def greetings(name, country):
    print(f"Hello  {name}! You're from {country}, right?")

In [364]:
greetings(name="Johan", country="Sweden")

Hello Johan! You're from Sweden, right?


When specifying argument to parameters as in the cell directly above, note that we don't use blank space inbetween the `=`. 

Some of you might have noticed that this is different than when we defined variables in section 3 above. If we would simply define a variable like this:

In [339]:
name = "Johan"

...we use one blank space on each side of the `=` operator. It is common practice to _not_ use blank space when specifying parameters in function calls:

In [340]:
greetings(name="Johan", country="Sweden") # No blank spaces next to the "=" operators!

Hello Johan! You're from Sweden, right?


However, there IS blank space after the comma. All this is common practice in the Python community, since it is considered to increase your code's readability. It is would still work with blank space:

In [365]:
greetings(country = "Sweden", name = "Johan") # don't write like this, even though it works :)

Hello Johan! You're from Sweden, right?


Why? This is in accordance with [the official Python style guide.](https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements)

Lastly, since the function `greetings()` _requires_ two argument – that is, two **positional arguments** – we shouldn't name them in our function calls. It is seen as overly wordy and verbose. So this is prefered:

In [366]:
greetings("Johan", "Sweden")

Hello Johan! You're from Sweden, right?


### The `return` statement

Just having functions printing information may not be sufficient when you write a function. Often, you want your function to do something to the values – the arguments, that is – that we pass to them. You want them to _return_ a result of some kind. We can specify what to be returned from functions we write using the `return` statement. As an example, we will build a small calculator!

In [373]:
def multiplies_by_three(number):
    number = number * 3
    return number

In [374]:
multiplies_by_three(5)

15

Let's go through this step by step:
1. We have defined a new function that we named `multiplies_by_three`
2. We've specified that the function has a parameter – `number`
3. The functions code block then multiplies the `number` parameter by three, and reassigns the results to the variable `number`
4. It then _returns_ the resulting number value that is assigned to `number` using the `return` keyword. _This is the return statement_
5. Finally, we call our function, passing it the integer value 5 as an argument. It runs the integer through the function's code block and returns the value 15

We can save this result in a new variable:

In [375]:
results = multiplies_by_three(5)

In [376]:
results

15

Actually, a function _always_ return a value. But if you don't specify which one with a return statement, it will return the `None` value. See what happens if we only remove the result statement:

In [379]:
def multiplies_by_three(number):
    number = number * 3

In [380]:
results = multiplies_by_three(5)

In [382]:
results # Doesn't return anything?

In [384]:
type(results)

NoneType

In [385]:
None == results

True

### Exercise – the currency converter

In this exercise, we shall build a function that takes two arguments. The first is a number value specifying an amount of euros, and the second is a string value specifying which currency we want to convert into (preferably the currency codes). 

So, if we pass our function the arguments `2000` and `"USD"`, the function shall return the amount 2000 euros converted into American dollars. The function should be able to calculate at least four different currencies:
- Swedish krona (SEK), 1 euro equals 10.43 Swedish krona
- American dollar (USD), 1 euro equals 1.17 American dollars
- British Sterling Pound (GBP), 1 euro equals 0.92 British pounds
- Chinese Renminbi (RMB), 1 euro equals 7.89 renminbis

Remember to try to write the function as zen-like (also called "pythonic") as possible! For example, name your parameters in a logical manner :) 

The solution is found in the solutions notebook. Good luck!

### Bulletpoints

- Functions are small miniprograms. They are containers of block of code. They help us not having to dublicate code
- We **call** functions by **invoking** them, which means we write their names followed by enclosed parenthesis
- We can pass values to function when invoking them. These inputs are called **arguments**
- The arguments' values are assigned to the function's **parameters**, which are then used as variables within the function's code block
- By invoking functions, it **returns a value as an output**. We can specify what in the function we want returned by using **the return statement**

## Local and global scopes

Hopefully, you now understand how to use and how to build your own functions, and how they are useful when coding in Python. But there is one concept we havn't introduced that is essential to understand when writing functions in Python: _scopes_.

The code that is executed outside a function is in a different scope than the code living inside it. Take this function that creates a variable assigned to the integer 9, and then returns it:

In [430]:
def make_nine():
    number = 9
    return number

Let's try it!

In [432]:
make_nine()

9

When we called the function, the code block within it was executed, and the integer 9 was returned. But what happens if we first create a variable outside the function, assigned to another variable:

In [434]:
number = 3

In [435]:
number

3

...and now run the function again:

In [436]:
make_nine()

9

So, if we now check the variable `number`, which value will we get? Can you guess?

In [437]:
number

3

_Why is this?_ 

We first created the variable `number` outside the function. This happend in the scope "furthest outside" – the ground level sort to speak – and this is called **the global scope**. There is no scope outside the global scope. Variables that are created in the global scope are called **global variables**.

The code that lives within the function is in a **local scope**. When the function is invoked, the code inside the function is executed in _a local execution context_. This means that the variable `number` we created inside the function is within in a different context than when we defined the global variable `number = 3`, in the global scope. Variables defined inside a function – inside the function's local scope – are called **local variables**. 

**Variables cannot be both local and global.**

Here's the same code, but with some comments to highlight scopes:


In [441]:
def make_nine():
    # This code block is in a local scope
    number = 9 # Local variable
    return number # The local scope terminates after this line

number = 3 # Global variable

make_nine() # This executes the code within the function, creating a local scope

number # This is still our global variable


3

When `number` is defined in the `make_nine()` function, it only lives in this local scope. When the last line within the function is executed, the local scope is terminated and all variables defined gets forgotten.

Here is a picture visualising what was going on:

<img src="course_material/scopes.png" style="width: 600px;"/>

1. We defined a function called `make_nine()` that creates the local variable `number`
2. We created the global variable `number` – this happend in the global scope
3. We call the function
4. By invoking the function, a local scope is created and the code within the function executes
5. The _local_ variable `number` gets set to a new value – the integer 9 – but this happens within the local scope, _it is a different variable than the global variable `number`_
6. The integer value 9 is returned by the function and the local scope is terminated and `number = 9` is forgotten
7. Finally, we run the _global_ variable `number` which returns the integer 3 since this is the value the global variable `number` points to

Let's include som `print()` functions to make it even clearer:

In [442]:
def make_nine():
    number = 9 # local variable
    print("Local scope: now, number is " + str(number))
    return number

In [444]:
number = 3
print("Global scope: number is " + str(number))

# we now call the function, creating a local execution context
make_nine()

print("Global scope: finally, number is still " + str(number) + " in the global execution conte")

Global scope: number is 3
Local scope: now, number is 9
Global scope: finally, number is still 3 in the global execution conte


Here are some general rules concerning scopes:

### Global code cannot use local variables

Take this example:

In [455]:
def define_a_variable():
    # This code is in a local scope
    local_num = 42

In [456]:
# calling the function, creating its local scope
define_a_variable()

In [454]:
local_num # error, since there is no such variable in the global scope

NameError: name 'local_num' is not defined

The variable `local_num` doesn't exist in the global scope, it only exists briefly locally when the function is called and the functions code is run. When the function's code block is executed, the local scope terminates and the local variable is forgotten. So when we try to reference that variable in the global scope, the computer has no variable called `local_num` defined in memory. 

### Global variables can be used in local scopes

All local scopes can access variables that exists in the global scope. Take this example:

In [464]:
def a_function():
    print(fruit)

In [465]:
fruit = "Banana"

Above, we have a function that only prints a variable named `fruit`. When we call `a_function()`, the interpreter sees that we want to print a variable. But since we havn't created any such variable locally within the function, the interpreter checks to see if any such variable exists in the global scope. So if we run the function:

In [466]:
a_function()

Banana


...it returns the value of the global variable `fruit`.

So the rule is: if there is no `assignement statement` within a local scope, and a variable is referenced, the interpreter will check for any variable with the same name in the global scope and then use it.

### Local scopes can't use variables in other local scopes

Let's define two functions that can explain this fact:

In [457]:
def function_one():
    big_number = 99
    function_two()
    print(big_number)
    
def function_two():
    big_number = 9000

Here, we have two functions. `function_two()` is called within the scope of `function_one()`. If we call `function_one()`, which number do you think will be printed? Let's have a look:

In [458]:
function_one()

99


When we call `function_one()`, the variable `big_number` is assigned to the value 99. And after that `function_two()` is called, creating its own local scope. Within this scope, `big_number` is assigned to the value 9000 – _but this is another variable than the one in `function_one()`._ They are in different local scopes, and therefore not the same variable.

After `big_number` is defined in `function_two()`, the function is finished and its local scope terminated. The local variable `big_number` in `function_two()` is consequently lost. The interpreter then returns to the local scope within `function_one()` and prints `big_number` – which in _this_ scope is assigned to 99.

The two functions' scopes are not connected and thus, their variables are not interchangable. Let's create a variable in `function_two()` that isn't in `function_one()` and then try to reference it:

In [459]:
def function_one():
    function_two()
    print(fruit)
    
def function_two():
    fruit = "Banana"

In [460]:
function_one()

NameError: name 'fruit' is not defined

We get a `NameError` since the variable `fruit` doesn't exist within the local scope of `function_one()`, only within `function_two()`'s.

### Exercise – why won't the code work?

We have this code:

In [46]:
def print_results(results):
    print(f"{str(number1)} multiplied with {str(number2)} is {results}")

def calculator(number1, number2):
    results = number1 * number2

num_apples = 5
num_oranges = 6

calculator(num_apples, num_oranges)
print_results(results)


NameError: name 'results' is not defined

Explain with your own words why the above code doesn't work. Reminder: If you mark a cell in a Jupyter notebook and press <kbd>M</kbd>, the cell will be a text cell (in Markdown) in which you can write down your explaination.

You'll find the solution in the solutions notebook. Good luck!

## Object orientation and Methods

In Python, everything, all code, is considered an object. Every object comes with its own features, properties, and functions. This means that if we create a variable with a string value:

In [48]:
fruit = "banana"

...this variable has its own functions. A function connected to an object is called a **method** in Python. They are exactly the same as the regular functions we have learned about in the previous chapter, only that they are accessed in a different way – with the dot `.` operator. We actually used the `.` operator when we learned about how to import modules and to use their functions when we imported the `randint()` function from the `random` module. Using the `.` to access method is called **dot notation**.

In [484]:
import random

In [486]:
random.randint(1,10) # randint() is a method

10

Since even values are objects with their own methods, let's try it on our variable's string value. We can use string value methods! For example, the `upper()` method:

In [488]:
fruit.upper() # returns the string in upper casing

'BANANA'

Or the `capitalize()` method, which returns the string but with the first letter capitalized:

In [491]:
fruit.capitalize()

'Banana'

Remember, methods and functions are the same. "Method" is used to emphasize that it is a function attached to other objects.

### Exercise – experiment with string methods

In this exercise, I want you to experiment with string methods. I want you to try out dot notation after this string variable:

In [57]:
fruits = "There are at least two bananas in this sentence bananas"

Remember that dot notation is when you type the variable name, and then a dot `.` after. So in this case, you write `fruits.`. In Jupyter Notebooks, you can then press the <kbd>⇥ Tab</kbd> key to get a list of all methods available for the variable. If you want to see the methods docstring (information about the method), you can write the variable with dot notation, the method and then press <kbd>Shift ⇧</kbd>+<kbd>⇥ Tab</kbd> to get access to the docstring. So, as an example, if you want the docstring for the string method `.upper()`, you type `fruits.upper` and then tap <kbd>Shift ⇧</kbd>+<kbd>⇥ Tab</kbd>!

Using the variable above, I want you to find out what these three methods do, and then use them in an example of your own:

1. `.count()`
2. `.find()`
3. `.replace()`

Good luck!

## Lists

In section 1, we learned about the different value types. When programming, we often want to save many values into a container to store data. These are called **data structures**. In Python there The main data structures in Python is:

- lists
- tuples
- dictionaries

In this chapter, we will learn about lists and save the other two for later chapters.

### Definition

A list in Python is defined by enclosed within square brackets `[]`:

In [82]:
[] # empty list

[]

In [467]:
type([])

list

A list can contain zero (like in the cell just above), one, or many values. The contents in a list are called **items**. All items in a list are seperated by commas:

In [497]:
[2, 4, 3, 1]

[2, 4, 3, 1]

(Note that it is common practice to type blank space after commas in lists in Python)

Lists can contain any type of value:

In [469]:
[1, "Hello world!", True, None]

[1, 'Hello world!', True, None]

### List index

All lists in Python has an index that can be used to find specific values within the list.

In [506]:
a_list = [1, 2, "three", 4] # saving a list to a variable

To access a list's index and return a specific value, we type squared brackets directly after the list with an **index number** in-between:

In [507]:
a_list[0]

1

In [508]:
a_list[2]

'three'

In Python, lists are zero-indexed, meaning that their index start at 0. But we can also reference the index using negative numbers which references the list backwards. **Negative indexing** start at -1 which points to the last value in the list:

In [509]:
a_list[-1]

4

Using an indexnumber that is higher than the number of values included in the list will produce an error:

In [510]:
a_list[10]

IndexError: list index out of range

You can also put lists within lists. This is called _nested lists_:

In [498]:
nested_list = [0, 1, [2, 3], 4]

Nested lists' values can also be accessed with indexing:

In [503]:
nested_list[2] # index value 2 returns the nested list

[2, 3]

In [504]:
nested_list[2][1] # second index value (1) returns the second item in the nested list

3

### Slicing

Using index values, we can also get chunks of the list. This is done with **slicing**. The syntax for a slice is two index numbers – a start and a stop index – seperated by a colon `:`

In [544]:
a_list = [3, 5, 4, "banana", "apple", "orange"]

In [545]:
a_list[3:6] # start at index 3, stop at index 6

['banana', 'apple', 'orange']

The second number is "up to this index", **not** "up to _and including_ this index". 

We can also do slicing with just one index number:

In [549]:
a_list[:2] # returns all values up to index 2

[3, 5]

In [551]:
a_list[2:] # returns all values from index 2 and onwards

[4, 'banana', 'apple', 'orange']

_A slice always returns a list_, even if you would only get one value from it:

In [546]:
a_list[-1:] # return all values from the last value and onwards

['orange']

### Changing list values

Using list indexing, we can also change values within the list:

In [4]:
fruit = ['banana', 'apple', 'pear']

In [5]:
fruit[1] = 'peach'

In [6]:
fruit

['banana', 'peach', 'pear']

This can also be done using slicing:

In [7]:
fruit[1:] = ['blueberries', 'orange']

In [8]:
fruit

['banana', 'blueberries', 'orange']

### Removing items with `del`

Removing items can also done using the `del` keyword:

In [16]:
fruit = ['banana', 'apple', 'pear']

In [17]:
del fruit[1]

In [18]:
fruit

['banana', 'pear']

Can also be used with slicing:

In [25]:
fruit = ['banana', 'apple', 'pear', 'orange']

In [26]:
del fruit[0:2]

In [27]:
fruit

['pear', 'orange']

### List methods

Lists have a range of useful methods. These are some commonly used ones.

#### `.append()`

Take this list as an example:

In [84]:
animals = ["dog", "camel", "bird", "mouse"]

In [85]:
animals

['dog', 'camel', 'bird', 'mouse']

With the `append()` method, we add the passed argument to the end of the list. Here, we add the string "elephant":

In [86]:
animals.append("elephant")

In [87]:
animals

['dog', 'camel', 'bird', 'mouse', 'elephant']

#### `.insert()`

Using the `insert()` method, we also add a value, but we can specify where we want it placed inside the list. This method takes two arguments (seperated by comma, remember?): the first is the index number we want the new value placed, and the second is the value we want inserted in the list.

In [95]:
animals = ["dog", "camel", "bird", "mouse"]

In [96]:
animals.insert(2, "elephant") # value with index number 2 – that is, the third value – shall be "elephant"

In [97]:
animals

['dog', 'camel', 'elephant', 'bird', 'mouse']

#### `.remove()`

We can also remove items using the `remove()` method:

In [98]:
animals = ["dog", "camel", "bird", "mouse"]

In [99]:
animals.remove("dog")

In [100]:
animals

['camel', 'bird', 'mouse']

#### `.index()`

We can also use the `index()` method to learn which index number a specific value in the list has:

In [83]:
animals.index('bird')

1

This can be useful when you only want one specific value changed, but don't know where in the list it is. Let's say we have a list of names, and only want to change one name in the list:

In [101]:
names = ["Johan", "Fredrik", "Anna", "Sonya", "Ahmed"]

In [102]:
change_this = names.index("Johan")

In [103]:
names[change_this] = "Super Fantastic"

In [104]:
names

['Super Fantastic', 'Fredrik', 'Anna', 'Sonya', 'Ahmed']

#### `.sort()`

The `.sort()` method sorts your list! Strings alphabetically:

In [1]:
names = ["Johan", "Fredrik", "Anna", "Sonya", "Ahmed"]

In [3]:
names.sort()

In [4]:
names

['Ahmed', 'Anna', 'Fredrik', 'Johan', 'Sonya']

Number values get sorted with the smallest value first:

In [12]:
numbers = [4, 53, 100, -14, 10, 10.1, 37]

In [13]:
numbers.sort()

In [14]:
numbers

[-14, 4, 10, 10.1, 37, 53, 100]

You can also use sort in reverse order, by setting the reverse parameter to `True`:

In [15]:
numbers.sort(reverse=True)

In [16]:
numbers

[100, 53, 37, 10.1, 10, 4, -14]

Sorted will produce an error if you try to sort a list with _both_ number and string values:

In [17]:
mixed = ["Johan", 4, "bananas", 42]

In [18]:
mixed.sort()

TypeError: '<' not supported between instances of 'int' and 'str'

##### ASCII Sorting

The `.sort()` doesn't actually sort by alphabetical order, but ASCII-betical order. This means it takes upper and lower casing into account while sorting. So upper case comes before lower case:

In [19]:
things = ["Johan", "Sarah", "Mohamed", "juice", "sand", "moose"]

In [20]:
things.sort()

In [21]:
things

['Johan', 'Mohamed', 'Sarah', 'juice', 'moose', 'sand']

In [24]:
things = ["AAA", "bbb", "CCC", "aaa", "BBB", "ccc"]

In [25]:
things.sort()

In [26]:
things

['AAA', 'BBB', 'CCC', 'aaa', 'bbb', 'ccc']

You can change the sorting behaviour to true alphabetical order by using the `key` parameter:

In [27]:
things = ["AAA", "bbb", "CCC", "aaa", "BBB", "ccc"]

In [28]:
things.sort(key=str.lower) # here, we're actually passing a method as an argument

In [29]:
things

['AAA', 'aaa', 'bbb', 'BBB', 'CCC', 'ccc']

In above sorting, casing is ignored. If the items are of the same alphbetical letters, they are ordered as they appear in the list.

#### (Optional) Method call straight into index brackets

Since the method `.index()` return the index value, we can acctually just insert that method call into the index brackets directly!

In [105]:
names = ["Johan", "Fredrik", "Anna", "Sonya", "Ahmed"]

In [106]:
names[names.index("Johan")] = "Super Fantastic"

In [107]:
names

['Super Fantastic', 'Fredrik', 'Anna', 'Sonya', 'Ahmed']

#### "In place" methods

Some of you may have noticed that some of the methods above didn't return any value. Take `.append()` as an example:

In [108]:
names = ["Johan", "Fredrik", "Anna", "Sonya", "Ahmed"]

In [109]:
names.append("Lisa") # Doesn't return anything??

In [110]:
names

['Johan', 'Fredrik', 'Anna', 'Sonya', 'Ahmed', 'Lisa']

Some methods modify values "in place". `.append()` is one such method. They actually do return a value – `None`. In other words, don't try to reassign the `.append()` method to the `names` variable: 

In [115]:
names = ["Johan", "Fredrik", "Anna", "Sonya", "Ahmed"]

In [112]:
names = names.append("Lisa")

In [113]:
names

In [114]:
type(names)

NoneType

### The built-in function `list()`

The `list()` function lets us convert list-like objects – containers – into Python lists. String values are containers, so the `list()` function divides the string into a list of all its characters:

In [57]:
list("Johan")

['J', 'o', 'h', 'a', 'n']

### The `in` and `not in` operators

Often, our lists will include a whole bunch of items. And it is fairly common we want to check to see if a specific value is or isn't included in the list. As an example, let's create a list of surnames:

In [63]:
surnames = ["Ekman", "Smith", "Deboullie", "Mäki", "Sørensen", "Doe"]

We can now check to see if the surname "Doe" is in the list (remember, Python is checking your code literally. Casing matters, so always check your spelling!):

In [68]:
"Doe" in surnames

True

In [69]:
"banana" not in surnames

True

In [70]:
"Doe" not in surnames

False

If you recall the if-statement, it is fairly easy to understand why these operators would come in handy in a program. Let's say we want our program to add names that aren't already in the list. An if-statement can help us with that:

In [78]:
name = "Sauron"

In [79]:
if name not in surnames:
    surnames.append(name)

In [80]:
surnames

['Ekman', 'Smith', 'Deboullie', 'Mäki', 'Sørensen', 'Doe', 'Johan', 'Sauron']

### Similarities between lists and strings

As explained in chapter 3 (Functions), the `len()` function returns the number of items within a container. We used this built-in function on string values:

In [35]:
name = "Johan"

In [36]:
len(name)

5

String values actually have a lot in common with lists. They have an index:

In [37]:
name[2]

'h'

You can use slice indexing:

In [38]:
name[2:4]

'ha'

Just like lists, you can use the `in` and `not in` operators on strings:

In [30]:
# returns True if "oh" is in the string
"oh" in "Johan"

True

In [31]:
# returns True if "Johan" isn't in the string
"Johan" not in "This is a string value, not containing any names."

True

In [32]:
# returns False if "Johan" is in the string
"Johan" not in "This is a string value, containing the name Johan."

False

And, as shown in section 9.7, if we use the `list()` function on a string, it returns the strings characters in a list:

In [39]:
list("Johan")

['J', 'o', 'h', 'a', 'n']

Just like strings, lists are also containers, which means we can also use the `len()` function on our lists!

In [61]:
fruit = ['banana', 'apple', 'orange']

In [37]:
len(fruit)

3

Just as with strings, lists can be concatinated with the `+` operator.

In [52]:
"Hello " + "world!"

'Hello world!'

This also works with lists:

In [53]:
fruit

['banana', 'apple', 'orange']

In [48]:
berries = ['blackberries', 'strawberries', 'blueberries']

In [49]:
fruit + berries

['banana', 'apple', 'orange', 'blackberries', 'strawberries', 'blueberries']

In [56]:
[1, 2, 3] + [4]

[1, 2, 3, 4]

We can also do **list replication** with the multiplication operator:

In [55]:
fruit * 3

['banana',
 'apple',
 'orange',
 'banana',
 'apple',
 'orange',
 'banana',
 'apple',
 'orange']

#### The `split()` method

String values acctually have a very neet method that let us cut up strings into lists: `split()`. By default, this method splits up the string by all its blank spaces:

In [41]:
long_string = "Hello everyone. This is a preeeetty long string. At least, I think so"

In [42]:
long_string.split()

['Hello',
 'everyone.',
 'This',
 'is',
 'a',
 'preeeetty',
 'long',
 'string.',
 'At',
 'least,',
 'I',
 'think',
 'so']

But we can split it on any character we wish. We just pass a character to split on as an argument:

In [58]:
long_string.split(".") # splits on '.'

['Hello everyone', ' This is a preeeetty long string', ' At least, I think so']

In [59]:
long_string.split("e") # splits on 'e'

['H',
 'llo ',
 'v',
 'ryon',
 '. This is a pr',
 '',
 '',
 '',
 'tty long string. At l',
 'ast, I think so']

Note that the character that we chose to split on isn't included in the returned list.

### Exercise – Build your own list function, part 1

In this exercise, I want you to build a function that replaces any of the values in this list: 

`my_list = ["apple", "pear", "orange", "blueberry"]`

It should have three parameters. the first should be the value that is meant to be replaced. The second should be the value we want to replace with, and the third should be the list itself. 

For example, say I want to swap `"orange"` to `"pineapple"`, your function should be called like this:

`my_function("orange", "pineapple", my_list)` and then return a list where `"orange"` is gone, and `"pineapple"` added to the list. 

Also! If the passed item isn't included in the list, the function should print a warning about this and then return the original list. 

Hint: you will need to use list methods to get this done. The solution can be found in the solutions notebook. Good luck!

In [63]:
my_list = ["apple", "pear", "orange", "blueberry"]

## Loops

### `while`-loops

In chapter 6 we learned about flow control `if`-statements. For example:

In [5]:
number = 0

In [6]:
if number < 5:
    number = number + 1
    print(number)

1


Here, we created a global variable `number` assigned to the integer 0. The `if`-statement evaluates the condition `number < 5` to `True` (since 0 is less than 5) and thus executes the code block beneath it. Within the code block, `number` is increased by 1, and the variable is then printed. Here is a flow chart of what has happend:

<img src="course_material/if_statement.png" style="width: 600px;"/>

A `while`-loop lets us use the same kind of flow control, while at the same time automatically repeating the code block as many times we'd like. Let's do the same thing, but with a while loop:

In [11]:
number = 0

In [12]:
while number < 5:
    number = number + 1
    print(number)

1
2
3
4
5


A `while`-loop evaluates the condition passed (`number < 5`), and if this is true, the code block is executed – just like the `if`-statement. BUT! The difference is that the `while`-loop will execute the code block, and then _return back to the condition and check it again_. If the condition is still true, it will rerun the code block. It will _loop over_ the code block until the condition is false! Here is a flow chart of what happend:

<img src="course_material/while_loop.png" style="width: 500px;"/>

While loops are usually used when you want input from a user that needs to be typed in a specific way. Uncomment the following code (just remove the `#` characters in the cell – and be careful to only remove the `#` characters!) and run the code:

In [19]:
#user_input = input()
#print("Would you like to proceed?")
#while user_input != "Yes":
#    print("To proceed, type 'Yes'")
#    user_input = input()
#print("Proceeding...")

Above, we use the built-in function `input()`. This creates a small input bar under the cell where we can type in a value that will be passed as a string to our code. If the string value we've passed doesn't match "Yes", the condition `user_input != "Yes"` will evaluate to `True`, and the code block is executed. 

#### CAUTION: Infinite `while`-loops

Since a while-loop always repeats itself if its condition is evaluated to True, you have to be cautious not to create an infinite loop. Let's reuse the above example but with one small change:

In [13]:
number = 0

In [ ]:
#while number < 5:
#    print(number)

The while-loop above is commented out so that you won't run it by accident. This code will create an infinite loop. Since we no longer add the integer 1 to `number` within the loop's code block, `number` will always be 0. This means that the condition `number < 5` will _always_ be True, and the loop will continue until the end of time. Whoopsie! ¯\\\_(ツ)\_/¯

No worries though. You can _always_ interrupt a running program in Python. In general, when running python programs, this is done by pressing <kbd>⌃ Control</kbd>+<kbd>C</kbd>. In a Jupyter Notebook, however, you do this by either:
- pressing <kbd>I</kbd>,<kbd>I</kbd> (double tap `I` on your keyboard)
- Go to the Jupyter menu and choose Kernel > Interrupt. Here is a pic:

<img src="course_material/interrupt.png" style="width: 500px;"/>

Try it! Uncomment above while-loop and interrupt it!

#### The `break` statement

The `break` statement cancels a ongoing loop. Let's use the `sum()` function in this example. It sums up a list's number values:

In [73]:
number_list = [1, 2, 3, 4, 5, 6]

In [70]:
sum(number_list)

21

Let's say we want to increase the first value in the list by one until the sum of all values is 1000. This can be done with a while loop:

In [71]:
while sum(number_list) < 1000:
    number_list[0] += 1 # remember this? Section 3.3.1!

In [72]:
number_list

[980, 2, 3, 4, 5, 6]

But let's say that, for whatever reason, we want the loop the stop if it's taking too long. So, if the first value in the list is too small – like, less than 100 – this while loop is gonna be too slow and we want it to stop. We can then use a `break` statement:

In [74]:
number_list = [1, 2, 3, 4, 5, 6]

In [76]:
while sum(number_list) < 1000:
    if number_list[0] < 100:
        print("First list item is less than 100. Stopping loop...")
        break
    number_list[0] += 1 # remember this? Section 3.3.1!

first item is less than 100. Stopping loop...


In [77]:
number_list

[1, 2, 3, 4, 5, 6]

Another example: let's say we have a list of names, and we want to use a while loop to remove all "Johan" in the list, using the `.remove()` method:

In [89]:
list_of_names = ["Johan", "Fredrick", "Jonas", "Katie", "Puck", "Johan"]

In [90]:
name = "Johan"

The `.remove()` method only removes the lowest indexed occurance of the passed argument. So if I pass "Johan", only the first occurance will be removed from the list:

In [91]:
list_of_names.remove(name)

In [92]:
list_of_names

['Fredrick', 'Jonas', 'Katie', 'Puck', 'Johan']

But we can use a while loop to remove all the occurances, using the `.index()` method instead:

In [93]:
list_of_names = ["Johan", "Fredrick", "Jonas", "Katie", "Puck", "Johan"]
while name in list_of_names:
    list_of_names.remove(name)

In [94]:
list_of_names

['Fredrick', 'Jonas', 'Katie', 'Puck']

But what if we don't want this to run on a list that is really really big? Say, larger than 10.000 items? We can use the `break` statment:

In [95]:
list_of_names = ["Johan", "Fredrick", "Jonas", "Katie", "Puck", "Johan"] * 5000

In [96]:
len(list_of_names)

30000

In [98]:
while name in list_of_names:
    if len(list_of_names) > 10000:
        print("While-loop stopped because list too big...")
        break
    list_of_names.remove(name)

While-loop stopped because list too big...


#### Exercise – Build your own list function, part 2

In this exercise, we will redo our function from the last exercise, but with a while-loop instead of inplace list methods. As was in the last exercise, you will create a function that takes three arguments: the list item to replace, the replacement value, and the list itself. But this time, the function should be able to take any list and replace all occurances of the values within the list, _at the same index where they lie in the list_.

Take this list as an example:

`my_list = ["orange", "pear", "orange", "blueberry"]`

Say we want to replace "orange" with "pineapple", the return from your function should look like this:

`["pineapple", "pear", "pineapple", "blueberry"]`

This function should also print a warning if the item to replace isn't in the list passed to the function.

Hint: you can solve this using these following mechanics (together with other things we've learned):
- a while-loop
- the `.index()` list method

You won't need the methods `.remove()` and `.append()`.

As always, the solution can be found in the solutions notebook. Good luck!

### `for`-loops

In chapter 10 we learned about lists. A very common task in coding is looping through all items in a list to change all, or some, of the values within it. If we don't use a loop, going through the list items will be tedious and ugly.

As an example, let's say we have a list of values, and we want to multiply them with three and print the results:

In [4]:
numbers = [42, 3, 15, 7, 99]

Using the list's index, we can do operations on the list's values:

In [2]:
result = numbers[0] * 3
print(result)
result = numbers[1] * 3
print(result)
result = numbers[2] * 3
print(result)
result = numbers[3] * 3
print(result)
result = numbers[4] * 3
print(result)

126
9
45
21
297


As you can see, this is as boring to type out as it is hard to read. Instead, we can use the `for`-loop. There are two ways to loop through the items:
- either going through them by index, using the `range()` function
- looping the actual values in the list, wihtout the `range()` function

Let's go through them one by one.

#### `for`-loop with the `range()` function

The `range()`-function returns what is called a range object. It can be used together with a loop to set how many loops we wish to be called:

In [11]:
type(range(5)) # the range datatype

range

In [12]:
for i in range(5):
    print(i)

0
1
2
3
4


A for loop consists of five pieces:
1. The `for` keyword
2. A variable name. `i` in the above example (this is the standard way to name the variable in for-loops using the range() function – "i" for index)
3. The `in` keyword, specifying which container object we want to loop over
4. The container to loop over (in this case, a range object returned from the `range()`-function)
5. A colon `:` signifying "the following code block shall be used in every loop"


As explained in (2), the variable name can be set to whatever. But it is common practice to name it `i` for `index` if using the range function. So the above code tells the interpreter. Here is another example, just to show you that the variable can be named whatever (in general, don't do this):

In [27]:
for johan in range(3):
    print("johan is: " + str(johan)) # have to use the str() function to be able to do string concatination

johan is: 0
johan is: 1
johan is: 2


In [28]:
for index in range(3):
    print("index is: " + str(index))

index is: 0
index is: 1
index is: 2


In [29]:
for i in range(3):
    print("i is: " + str(i))

i is: 0
i is: 1
i is: 2


If the `range()` function is only given one argument, it will give you the number of loops – or **iterations** as its more commonly refered to – up to this index number. As you can see above, the argument 3 gives us three iterations, since it goes up to, not including, this index number: 0, 1, 2.

But you can give the `range()` function more than one argument. If you give it two arguments, the first will be the start value, and the second the stop value:

In [30]:
for i in range(5, 10):
    print("i is: " + str(i))

i is: 5
i is: 6
i is: 7
i is: 8
i is: 9


So, above the range function gave us 5 iterations: starting at 5 and stopping at 10, which is 9. Note that only passing it one argument, the default starting value will be 0. 

But we can also give the function a third argument: how big steps we want each iteration to take:

In [31]:
for i in range(50, 100, 10):
    print("i is: " + str(i))

i is: 50
i is: 60
i is: 70
i is: 80
i is: 90


To make this even clearer, we can acctually pass this range object to the `list()` function and get a new list:

In [34]:
list(range(50, 100, 10))

[50, 60, 70, 80, 90]

In [35]:
list(range(5))

[0, 1, 2, 3, 4]

In [37]:
list(range(0)) # zero iterations gives us an empty list

[]

So how do we then use the `range()` function to loop over our list of numbers? Well, the reason it is common practise to name the loop variable `i` is because this variable can be used as an index number in another list. Let's try it on our list:

In [38]:
numbers = [42, 3, 15, 7, 99]

In [33]:
for i in range(5):
    print(numbers[i])

42
3
15
7
99


Hang on? What the hell just happend??

We created a for-loop with a `range()` function as our container to loop over. Passing it the argument 5 specfifys five iterations, starting at 0. So in the first loop, our for-loop variable will be 0, that is `i = 0`. When we pass the variable `i` as an index value to our list, this will be the same as typing `numbers[0]` in the first loop. `numbers[1]` the second loop, `numbers[2]` the third, and so on.

So, back to our problem from earlier. We want multiply each value in our list by 3. And we don't wanna do this:

In [39]:
result = numbers[0] * 3
print(result)
result = numbers[1] * 3
print(result)
result = numbers[2] * 3
print(result)
result = numbers[3] * 3
print(result)
result = numbers[4] * 3
print(result)

126
9
45
21
297


Let's instead use a for-loop together with a `range()` function:

In [41]:
for i in range(5):
    result = numbers[i] * 3
    print(result)

126
9
45
21
297


Success! But let's make it a bit more clean. First of all, it is not recommended to actually specify the `range()`-argument in this way. Let's say we would have a lists containing hundreds of values. In that case, it wouldn't be very convenient to keep track of the exact number of items in the list. Specifying a too large number of iterations will give us an error:

In [45]:
for i in range(6):
    result = numbers[i] * 3
    print(result)

126
9
45
21
297


IndexError: list index out of range

So instead of using an actual number, we could use the length of the list itself! We can get the length using the `len()` function:

In [46]:
len(numbers)

5

Let's use this instead of the integer five as an argument in the `range()` function:

In [49]:
range(len(numbers))

range(0, 5)

Since `len(numbers)` returns 5, above is exactly the same as `range(5)`:

In [50]:
range(len(numbers)) == range(5)

True

While we're at it, let's rewrite the code block and make it a bit more concise. We don't actually need the variable `result`. We can just pass the expression `numbers[i] * 3` as an argument to our `print()` function:

In [51]:
for i in range(len(numbers)):
    print(numbers[i] * 3)

126
9
45
21
297


Et voilá! Instead of typing our each calculation for each value in our list, we used a for-loop (with a range function) to do it all in two lines of code! Well done!

Now, let's do it again. But this time without the `range()`-function call.

#### The `continue` statement

Above, we covered the `break` statement which let's us cancel the loop in certain circumstances. But let's say that we don't want the loop to completely stop, just skip the current iteration? This is where we can use the `continue` statement. Take this following example:

In [101]:
numbers = [1, 2, 3, 4, -1, 5, 6]

In [102]:
for i in range(len(numbers)):
    print(numbers[i])

1
2
3
4
-1
5
6


Let's say we don't want the loop to to print negative numbers. This is when we can use the `continue` statement. Using the same for-loop:

In [103]:
for i in range(len(numbers)):
    if numbers[i] < 0:
        continue
    else:
        print(numbers[i])

1
2
3
4
5
6


So each iteration in the for-loop starts with the if-statement. If the current iteration's list item is less than 0, the `continue` statement just abrubts the iteration and starts the next one. That's why the value -1 never gets printed.

Continue-statements are very handy since it allows us to choose which items in a list we want to change, by skipping the ones we're not interested in. In most situations where we need to fix an issue with the general problem "while looping over this list, if this particular value is like that, change it; _otherwise continue_".

##### Exercise – Build your own list function, part 3

Try to do exactly as in the last exercise, but with a for-loop (using the `range()` function) instead of a while-loop. Remember to also use the `len()` function! Also, the `continue` statement!

The solution can be found in the solutions notebook. Good luck!

#### `for`-loop without `range()`

For this exercise, we don't necessarily need the `range()` function call. The for-loop only need an container that can be used as an iterator, and our list variable `numbers` works fine by itself. Let's have a look:

In [53]:
for item in numbers:
    print(item)

42
3
15
7
99


Here, using the for-in-key word combination, we tell the interpreter that we want to iterate over all items in the list. As you can see, this is way more straight forward and easier to read than the solution using the `range()` function call.

In [54]:
for item in numbers:
    print(item * 3)

126
9
45
21
297


#### `for`-loops – with or without `range()`?

As you could see in the previous section. Typing for-loops without the range-function is way more readable and easier to understand. But does that mean we should always skip the `range()` function? The TDLR-version is: no. Sometimes we will need it.

Take this example: let's say we don't only want to print the calculations of the list's values. We instead want to change them to the calculations result. How would we do that, using a for-loop?

Here's a try without the range-function:

In [69]:
numbers

[42, 3, 15, 7, 99]

In [70]:
for item in numbers:
    item = item * 3
    print(item)

126
9
45
21
297


In [71]:
numbers

[42, 3, 15, 7, 99]

Hold up now! Nothing happend to the items in the list?? Why was that?

In each iteration in the for-loop, a variable named `item` is created. The list's value in the present iteration is then assigned to this variable – `item`. The variable `item` is then reassigned to the result of the calculation `item * 3`. Finally, the variable `item` is printed. But when the code block is executed, this variable `item` and its assigned value is forgotten and a new loop is initiated. 

In other words, _it isn't the actual list's value that is being changed. It is just a copy of it assigned to the variable `item`._ So the code `item = item * 3` has, in fact, no connection to the actual list and therefore, no changes to the list's values occurs.

However, we _can_ change the list's values if we reference them directly. If you recall section 10.3, changing a value within a list can be done by specifying the item's list index. _And this is where we will need the `range()` function!_

In [72]:
numbers = [42, 3, 15, 7, 99]

for i in range(len(numbers)):
    numbers[i] = numbers[i] * 3
    print(numbers[i])

126
9
45
21
297


In [73]:
numbers

[126, 9, 45, 21, 297]

Let's make it a bit tidier using an augment assignment operator instead (section 4.1.1, remember?):

In [74]:
numbers = [42, 3, 15, 7, 99]

for i in range(len(numbers)):
    numbers[i] *= 3
    print(numbers[i])

126
9
45
21
297


In [75]:
numbers

[126, 9, 45, 21, 297]

## Mutable and immutable objects

In chapter 9, we talked about the similarities between lists and string values. They are both objects that can be seen as containers. One big diffarence between strings and lists, however, is that string values are **immutable**, where as a list is **mutable**. In Python, if an object is immutable, it means that it cannot be changed after its creation. Take this following example:

In [105]:
cities = ["Stockholm", "Paris", "Kabul", "Sidney"]

Using indexing, we can change a specific value within the list. Let's say we want to change "Paris" to "Oslo":

In [106]:
cities[1] = "Oslo"

In [107]:
cities

['Stockholm', 'Oslo', 'Kabul', 'Sidney']

When working with string values, we can also use indexing to get characters returned:

In [24]:
name = "Johan"

In [25]:
name[1] # second letter in "Johan"

'o'

But what happends if we try to change an individual character within the string using indexing?

In [110]:
name[1] = "P"

TypeError: 'str' object does not support item assignment

We get an error! This is because string values are immutable. So if we want to change strings – and we do often want to change strings! – we create new strings:

In [112]:
name[0] + "P" + name[2:] # here using string concatination

'JPhan'

Immutability is a fundamental part of programming since there are many situations where you want certain parts of your code that cannot be altered. This is a bit abstract while learning programming, since we focus on small code snippets where things are easy to keep track of. But in a program with thousands of rows of code, objects' immutablility is an important aspect so we do not to confuse things. 

The reason for this is because its easy to mix up variables' **references**.

### Variables' references to values

Throughout this course, you might've wondered why I keep mentioning that variables "reference" a particular value, or "points" to a value. Why not that a variable _"is"_ a particular value? The reason is how the Python language works. When we create a variable, we are actually doing two things simultaneously: we create the value within the computers memory _and_ creating a namespace that _reference_ that value:

In [128]:
eggs = 5

So here, the integer 5 was created in the computer's memory. But we also told the computer "if we pass the name `eggs` to the interpreter, it should point to this integer". It is sort of like we create a value, and then hang a sign with the name "eggs" on it. Here's a pic visualising what's going on:

<img src="course_material/immutable_1.png" style="width: 500px;"/>

Let's copy the value 5 to another variable:

In [147]:
bananas = eggs

In [130]:
bananas

5

In [149]:
eggs == bananas

True

Both variables – `eggs` and `bananas` – are refering to _the same value_, the integer 5. In other words, we're not copying the actual value, we're just creating another sign – like a nametag – and slapping it on the same value:

<img src="course_material/immutable_2.png" style="width: 500px;"/>

We're creating a new reference to the value, rather than creating a new value!

But if we change the value `bananas`, we actually _do_ create a new value within the computer's memory, _and hanging our name sign on this new value instead_.

In [132]:
bananas += 1

In [135]:
eggs

5

In [133]:
bananas

6

So, now, the variable `bananas` points to the integer 6 – a new value within the computer's memory! Here's a pic:

<img src="course_material/immutable_3.png" style="width: 500px;"/>

This happens because integers are immutable. And if you think about it, this makes sense. The value 5 cannot also be the value 6. So, these two variables are now not the same since they point to two different values in the computer's memory.

In [150]:
eggs == bananas

True

Lists doesn't work the same way. Let's try a similar operation, but with two lists:

In [1]:
fruits = ["apples", "oranges", "grapes", "bananas"]

In [2]:
groceries = fruits

In [3]:
fruits

['apples', 'oranges', 'grapes', 'bananas']

In [4]:
groceries

['apples', 'oranges', 'grapes', 'bananas']

Here, we have a similar situation going on. We have created a value – this time a list – containing four string values, and we've slapped two nametags on this list:

<img src="course_material/mutable.png" style="width: 500px;"/>

Now, let's change one of the values within `groceries`:

In [5]:
groceries[2] = "MILK"

In [6]:
groceries

['apples', 'oranges', 'MILK', 'bananas']

If we now check `fruits`, the returned list may surprise you:

In [7]:
fruits

['apples', 'oranges', 'MILK', 'bananas']

...it has also been modified! Huh? What the hell happend??

When we changed the third value in the list to the string "MILK", this doesn't create a new list in the computer's memory. It is the same list, only with one of its items swapped. And since both variables `fruits` and `groceries` points to the same list (both the nametags are still attached to the same list), both variables return the altered list! 

<img src="course_material/mutable_2.png" style="width: 500px;"/>

**This is a really important concept to understand!** If you aren't familiar with this, your code's behaviour will sometimes confuse you. For example:

### Mutable lists in local scopes

Consider what we learned in chapter 7 – local and global scopes. Let's say we have a function that adds a value to a list

In [12]:
def adds_value(your_list):
    your_list.append("Hello world!")

As you might've noticed, this function doesn't have a return statement. This means that everything that happends in the function's local scope gets destroyed when the code block is exectued and the local scope terminated, right? Let's try it:

In [13]:
fruits = ["apples", "oranges", "grapes", "bananas"]

In [14]:
adds_value(fruits)

In [15]:
fruits

['apples', 'oranges', 'grapes', 'bananas', 'Hello world!']

Huh?? 

If you recall from chapter 7, the local scope in the function `add_value()` creates a variable named after the parameter `your_list`. And since this is in a local scope, all namespaces created in the function is lost when the function's code block is executed. 

But here's the thing: since a list is mutable, the variable `your_list` (that is created in the local scope) references _the same list_ as `fruits` is assigned to. And when we change the list value by adding a value, _it still is the same list value_. To continue our analogy of slapping a nametag on a value, we just hanged a new nametag on the same list value, only that it is in a local scope! Here's a pic that visualises what's going on:

<img src="course_material/mutable_scope.png" style="width: 500px;"/>

The local scope didn't create _a new list_, it only created a new nametag for the list – a new reference. And it is this namespace that then gets destroyed when the local scope is terminated. So the method `.append()` within the function's code block, actually altered the same list that the variable `fruits` points to. Therefore, when we run `fruits`, this global variable's list is also altered!

#### Exercise – why doesn't the variable change?

In this exercise, we have this function, similar to the one just above:

In [20]:
def add_value(number):
    number += 1

But when we call this function on the variable `apples` assigned to the number value 5, the value stays the same after the function call:

In [21]:
apples = 5

In [22]:
add_value(apples)

In [23]:
apples

5

This behaviour is different than what we saw with the function `add_value()` above, in section 11.2. Why is that? Explain in your own words what is happening here. The solution can be found, as usual, in the solutions notebook. 

Good luck!

### How to copy mutable objects then?

Obviously, there are many situations were we want to copy lists, and not only the reference. So how do we do that? There are a number of ways, and I will show you some, and then the way that is the best way.

First of, using the `.copy()` list method:

In [1]:
fruits = ["apples", "oranges", "grapes", "bananas"]

In [2]:
groceries = fruits.copy()

In [3]:
groceries[2] = "milk"

In [4]:
groceries

['apples', 'oranges', 'milk', 'bananas']

In [5]:
fruits

['apples', 'oranges', 'grapes', 'bananas']

Or, we could just use the `list()` function, creating a new list object:

In [6]:
fruits = ["apples", "oranges", "grapes", "bananas"]

In [7]:
groceries = list(fruits)

In [8]:
groceries[2] = "milk"

In [9]:
groceries

['apples', 'oranges', 'milk', 'bananas']

In [10]:
fruits

['apples', 'oranges', 'grapes', 'bananas']

Or, we can reference the original list's index and just type colon `:`, indicating we want all values. This also creates a new list object:

In [12]:
fruits = ["apples", "oranges", "grapes", "bananas"]

In [13]:
groceries = fruits[:]

In [14]:
groceries[2] = "milk"

In [15]:
groceries

['apples', 'oranges', 'milk', 'bananas']

In [16]:
fruits

['apples', 'oranges', 'grapes', 'bananas']

However, the way to go – if you need a completely new list object and no references intertwined – is using the `deepcopy()` function from the `copy` module. But we need to import it:

In [24]:
import copy

In [25]:
fruits = ["apples", "oranges", "grapes", "bananas"]

In [26]:
groceries = copy.deepcopy(fruits)

In [27]:
groceries[2] = "milk"

In [28]:
groceries

['apples', 'oranges', 'milk', 'bananas']

In [29]:
fruits

['apples', 'oranges', 'grapes', 'bananas']

This function is the supperior way to go, since it not only creates a new list object, but also nested lists. I won't go into more detail here, but if you're interested, [this is a good explanation!](https://realpython.com/copying-python-objects/)

## Tuples

Tuples are very similar to lists, only that they are defined with plain brackets `()`:

In [19]:
a_tuple = (1, "Hello world!", 3, 4)

In [20]:
a_tuple[1]

'Hello world!'

In [21]:
a_tuple[-1]

4

The big differance is that tuples are immutable:

In [22]:
a_tuple[1] = "eggs"

TypeError: 'tuple' object does not support item assignment

## Dictionaries

### Definitions

Another way to store data in Python is **the dictionary datatype**. It is defined by the curly brackets `{}`:

In [1]:
type({})

dict

Dictionaries consists of pairs of keys and values – **key-value pairs**. In lists, each value in the list had an index that you could call to return any specific item in the list. In dictionaries, there is no index, instead we have keys, and they can be any (immutable) value type.

We can create dictionaries, either with the dictionary literal syntax:

In [48]:
person = {"name":"Johan", "age":35}

...or with the `dict()` function call:

In [49]:
person = dict(name="Johan", age=35)

In [50]:
person

{'name': 'Johan', 'age': 35}

We can also just start with an empty dictionary (or _dict_ as it's sometimes called) and then add keys as we go:

In [56]:
person = {}

In [58]:
person['name'] = "Johan"
person['age'] = 35

In [59]:
person

{'name': 'Johan', 'age': 35}

Note that using the literal syntax, you can use as much whitespace as you want. This is simply ignored by the interpreter:

In [63]:
person = {
    "name":"Johan",
    "age":35
}

We use the dictionary keys instead of an index to get access to specific values within the dictionary. Take this example:

In [61]:
person['nationality']

'Swedish'

In [62]:
person['age']

35

We can store dictionaries within dictionaries, and then access those in one go. Take this example:

In [79]:
person = {
    "name":"Johan",
    "age":35,
    "nationality":"Swedish",
    "well-trained":False,
    "family": {
        "girlfriend": True,
        "children":True,
        "grandchildren":False,
        "parents": {
            "mom":True,
            "dad":True
        }
    }
}

Under the key `family`, the value now is a dictionary as well. So to access the values within, we just pile keys after one another to get the value we want:

In [75]:
person['family']['children']

True

In [76]:
person['family']['grandchildren']

False

In [78]:
person['family']['parents']['mom']

True

So, the syntax of the dictionary is: 
- it is enclosed within curly brackets `{}` 
- Each key-value pair is seperated with a comma `,`
- keys and values are set with colons `:`, with keys on the left side of the colon, and values on the right side 


A big differance compared to lists is that dictionaries don't have any particular order within them. Lists are ordered by index, so the placement of values within the list matters. Take this example:

In [26]:
["red", "yellow", "blue"] == ["yellow", "blue", "red"]

False

These two lists are not the same, since their indexed values don't line up. But if we have a two dictionaries which have the same key-value pairs within them, it doesn't matter where we place them within the curly brackets:

In [27]:
{"first":"red", "second": "blue"} == {"second": "blue", "first":"red"}

True

We can use the `in` and `not in` operators to see if certain keys are present within a dictionary:

In [10]:
"well-trained" in person

True

In [13]:
"potato" not in person

True

If we use the `.keys()` method, we get a list-like object of all keys within the dictionary:

In [14]:
person.keys()

dict_keys(['name', 'age', 'nationality', 'well-trained'])

A list-like object is a container of values that allows iteration, it's _sort of_ a list. You don't need to know this in detail, what this means that if we call the `list()` function on the method call, we get an actual list of the keys in the dictionary:

In [15]:
list(person.keys())

['name', 'age', 'nationality', 'well-trained']

If we use the `.values()` method, we get a list-like object of all values within the dictionary:

In [23]:
person.values()

dict_values(['Johan', 35, 'Swedish', False])

If we want all key-value pairs, we can call the `.item()` method that returns all keys and values in a list-like object with tuples:

In [25]:
person.items()

dict_items([('name', 'Johan'), ('age', 35), ('nationality', 'Swedish'), ('well-trained', False)])

### Looping over a dictionary

If we do a straight for-loop on our dictionary, it will loop over its keys:

In [64]:
person = {"name":"Johan", "age":35, "nationality":"Swedish", "well-trained":False}

In [65]:
for key in person:
    print(key)

name
age
nationality
well-trained


Which means we can loop the values by placing the `key` variable within square brackets after the dictionary:

In [66]:
for key in person:
    print(person[key])

Johan
35
Swedish
False


In the previous section, we briefly discussed dictionaries as unordered. This is actually not true in newer versions of Python. Ever since version Python 3.6 (this notebook is written in 3.8.5), **there is order in dictionaries** – they are organised in the same order you write them. But since this is a relatively new (albeit handy!) feature, you need to know how loops in dictionaries are commonly written, since otherwise, your programs might be buggy when used in older versions of Python.

The normal pattern for writing a for-loop over a dictionary is looping over its key-value pairs, using the `.items()` method:

In [67]:
for k,v in person.items():
    print(k,v)

name Johan
age 35
nationality Swedish
well-trained False


Hold up! Let's take it a bit slower now. Remember, the `items()` method returns a list-like object containing tuples of all key-value pairs within the dictionary:

In [35]:
list(person.items())

[('name', 'Johan'),
 ('age', 35),
 ('nationality', 'Swedish'),
 ('well-trained', False)]

If we loop over every tuple, each sequence will give us two values:

In [38]:
for tupl in list(person.items()):
    print(tupl)

('name', 'Johan')
('age', 35)
('nationality', 'Swedish')
('well-trained', False)


This is why, in our for-loop over the dictionary, we define two variables `k` and `v` for each loop, one for each value in every sequence in the loop. Maybe it is more apparent if add parenthesis and some string formatting to show you what's what:

In [39]:
for (k,v) in person.items():
    print(f"key: {k}, value: {v}")

key: name, value: Johan
key: age, value: 35
key: nationality, value: Swedish
key: well-trained, value: False


In [69]:
for (k,v) in person.items():
    if k == 'age':
        new_age = v + 1 # if the key is age, its value goes +1
        print(f"Next year, Johan turns {new_age}")
    else:
        print(f"This is not the 'age' key.")

This is not the 'age' key.
Next year, Johan turns 36
This is not the 'age' key.
This is not the 'age' key.


#### Exercise – the cheapest country, part 1

This exercise is a bit tricky. Here is a big dictionary with data of how expensive consumer goods and services are in various countries, in relation to eachother:

In [72]:
data = {'Albania': {2017: 51.4, 2018: 54.1, 2019: 56.9},
 'Austria': {2017: 111.8, 2018: 112.0, 2019: 113.0},
 'Belgium': {2017: 114.3, 2018: 114.8, 2019: 114.7},
 'Bosnia and Herzegovina': {2017: 54.5, 2018: 54.3, 2019: 54.8},
 'Bulgaria': {2017: 51.3, 2018: 52.0, 2019: 52.8},
 'Croatia': {2017: 69.5, 2018: 70.2, 2019: 71.2},
 'Cyprus': {2017: 90.3, 2018: 89.9, 2019: 90.1},
 'Czechia': {2017: 70.6, 2018: 73.4, 2019: 74.6},
 'Denmark': {2017: 143.3, 2018: 141.6, 2019: 141.3},
 'Estonia': {2017: 81.1, 2018: 83.0, 2019: 85.1},
 'Finland': {2017: 126.2, 2018: 126.0, 2019: 126.7},
 'France': {2017: 113.2, 2018: 113.6, 2019: 114.1},
 'Germany': {2017: 106.5, 2018: 106.8, 2019: 106.8},
 'Greece': {2017: 87.7, 2018: 86.5, 2019: 86.6},
 'Hungary': {2017: 65.0, 2018: 64.5, 2019: 65.3},
 'Iceland': {2017: 173.8, 2018: 162.4, 2019: 154.3},
 'Ireland': {2017: 131.2, 2018: 132.7, 2019: 133.7},
 'Italy': {2017: 103.8, 2018: 103.5, 2019: 102.7},
 'Japan': {2017: 121.7, 2018: 118.7, 2019: 124.1},
 'Latvia': {2017: 75.3, 2018: 76.5, 2019: 78.6},
 'Lithuania': {2017: 66.4, 2018: 68.0, 2019: 69.5},
 'Luxembourg': {2017: 129.0, 2018: 129.5, 2019: 131.1},
 'Malta': {2017: 84.9, 2018: 85.2, 2019: 87.3},
 'Montenegro': {2017: 57.1, 2018: 57.8, 2019: 57.1},
 'Netherlands': {2017: 115.0, 2018: 115.5, 2019: 116.5},
 'North Macedonia': {2017: 49.2, 2018: 49.9, 2019: 49.8},
 'Norway': {2017: 154.5, 2018: 151.1, 2019: 149.5},
 'Poland': {2017: 58.8, 2018: 59.6, 2019: 60.0},
 'Portugal': {2017: 89.2, 2018: 89.1, 2019: 87.9},
 'Romania': {2017: 53.9, 2018: 54.1, 2019: 54.9},
 'Serbia': {2017: 54.0, 2018: 55.7, 2019: 56.6},
 'Slovakia': {2017: 78.9, 2018: 79.7, 2019: 81.1},
 'Slovenia': {2017: 86.5, 2018: 87.2, 2019: 88.1},
 'Spain': {2017: 95.0, 2018: 95.7, 2019: 96.6},
 'Sweden': {2017: 128.9, 2018: 123.6, 2019: 120.6},
 'Switzerland': {2017: 163.8, 2018: 156.0, 2019: 162.0},
 'Turkey': {2017: 55.8, 2018: 45.9, 2019: 47.1},
 'United Kingdom': {2017: 119.9, 2018: 120.1, 2019: 121.2},
 'United States': {2017: 118.3, 2018: 114.0, 2019: 122.6}}

The bigger the number, the more expensive food, drinks, shopping etc. The value 100 indicates the average price for all European countries, each year.

By looping over this dictionary of data, I want you to find the country where consumer goods and services where the most expensive in 2019, and the country where it was the most cheap the same year.

Hint! Remember, you can create a `results` dictionary where you can compare, and swap values while looping over the data. Try out various ways to go and experiment! A solution is found in the solutions notebook!

### Dictionary methods `.get()` and `.setdefault()`

#### `.get()`

Hopefully, you can see why dictionaries are so important and useful in the Python language. But there are two methods that are good to know moving forward. They help us avoid errors where we try to check for a key in the dictionary, which isn't there:

In [42]:
person = {"name":"Johan", "age":35, "nationality":"Swedish", "well-trained":False}

In [43]:
person['height']

KeyError: 'height'

In such situations we get a key error. This isn't a huge problem with a small dictionary like ours, but imagine a way bigger one, in which we want to check for data automatically. If we try a key that isn't there, everything crashes. This is where we can use the `.get()` method. It takes two arguments, the first is the key we're looking for. The second is the default value we want returned if the key we asked for isn't in the dictionary! This way, we don't get an error:

In [44]:
person.get("height","The key 'height' isn't in this dictionary")

"The key 'height' isn't in this dictionary"

#### `.setdefault()`

But what if we want to add a key to the dictionary, but the key isn't in it? Same problem